DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE EVENT CASCADE CONSTRAINTS;
DROP TABLE ONE_QNA CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE ORDER_PRODUCT CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE QNA CASCADE CONSTRAINTS;
DROP TABLE PAYMENT_TBL CASCADE CONSTRAINTS;
DROP TABLE LOCATION CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE W_ORDER CASCADE CONSTRAINTS;
DROP TABLE CART CASCADE CONSTRAINTS;
DROP TABLE BRATTACHMENT CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_UNO; -- 회원
DROP SEQUENCE SEQ_PNO; -- 상품
DROP SEQUENCE SEQ_NNO; -- 공지
DROP SEQUENCE SEQ_ENO; -- 이벤트
DROP SEQUENCE SEQ_ONO; -- 1대1문의
DROP SEQUENCE SEQ_BNO; -- 게시판
DROP SEQUENCE SEQ_QNO; -- 문의
DROP SEQUENCE SEQ_ORDERNO; --주문 
DROP SEQUENCE SEQ_OPNO; -- 주문상세
DROP SEQUENCE SEQ_RNO; -- 리뷰
DROP SEQUENCE SEQ_CNO; -- 카트
DROP SEQUENCE SEQ_BRNO; -- 게시판용 파일



-- MEMBER 회원
CREATE TABLE MEMBER(
    USER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(15) UNIQUE NOT NULL,
    USER_PWD VARCHAR2(16) NOT NULL,
    USER_NAME VARCHAR2(30) NOT NULL,
    PHONE CHAR(13) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    ENROLL_DATE DATE DEFAULT SYSDATE,
    USER_SSN VARCHAR2(14) UNIQUE NOT NULL,
    BLACKLIST VARCHAR2(1) DEFAULT 'N' CHECK (BLACKLIST IN('Y','N')),
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y','N'))
);

CREATE SEQUENCE SEQ_UNO
NOCACHE;

INSERT INTO MEMBER 
VALUES (SEQ_UNO.NEXTVAL, 'admin', '1234', '관리자', '010-1111-2222', 'admin@kh.or.kr', SYSDATE, '921111-1111111', DEFAULT, DEFAULT);

INSERT INTO MEMBER 
VALUES (SEQ_UNO.NEXTVAL, 'user01', 'pass01', '홍길동', '010-1111-1111', 'user01@kh.or.kr', SYSDATE, '931212-2222222', DEFAULT, DEFAULT);

INSERT INTO MEMBER 
VALUES (SEQ_UNO.NEXTVAL, 'user02', 'pass02', '고길동', '010-1111-1411', 'user02@kh.or.kr', SYSDATE, '911111-2222222', DEFAULT, DEFAULT);
INSERT INTO MEMBER 
VALUES (SEQ_UNO.NEXTVAL, 'user03', 'pass03', '김뿅뿅', '010-4411-1111', 'user03@kh.or.kr', SYSDATE, '941212-2224222', DEFAULT, DEFAULT);
INSERT INTO MEMBER 
VALUES (SEQ_UNO.NEXTVAL, 'user04', 'pass04', '김한솔', '010-1111-1111', 'user04@kh.or.kr', SYSDATE, '941212-1111111', DEFAULT, DEFAULT);

-- 상품
CREATE TABLE PRODUCT(
	PRODUCT_NO NUMBER PRIMARY KEY,	
	PRODUCT_TYPE VARCHAR2(30) NOT NULL,
	PRODUCT_NAME VARCHAR2(60) NOT NULL,
	PRICE NUMBER NOT NULL,
	BRAND VARCHAR2(30) NOT NULL,
	ALCOHOL NUMBER NOT NULL,
	STOCK NUMBER NOT NULL,	
	ORIGIN VARCHAR2(30) NOT NULL,
	SWEETNESS NUMBER NOT NULL,
	ACIDITY NUMBER NOT NULL,
	BODY NUMBER NOT NULL,
	TANNIN NUMBER NOT NULL,	
	STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
	COUNT NUMBER DEFAULT 0,	
	THUMBNAIL VARCHAR2(1000),
	CONTENT_PHOTO1 VARCHAR2(1000),
	CONTENT_PHOTO2 VARCHAR2(1000),
	CONTENT VARCHAR2(4000)
);

-- 상품 내용을 사진으로만 채울 경우가 있으니까 CONTENT 부분은 NULL 가능하게 했습니다.

CREATE SEQUENCE SEQ_PNO
NOCACHE;


-- NOTICE 공지사항
CREATE TABLE NOTICE(
    NOTICE_NO NUMBER PRIMARY KEY,
    NOTICE_TITLE VARCHAR2(100) NOT NULL,
    NOTICE_CONTENT VARCHAR2(4000) NOT NULL,
    NOTICE_WRITER NUMBER NOT NULL,
    COUNT NUMBER DEFAULT 0,
    CREATE_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
    FOREIGN KEY (NOTICE_WRITER) REFERENCES MEMBER(USER_NO)
);

CREATE SEQUENCE SEQ_NNO
NOCACHE;

-- 카테고리
CREATE TABLE CATEGORY(
  CATEGORY_NO NUMBER PRIMARY KEY,
  CATEGORY_NAME VARCHAR2(30) NOT NULL
);

INSERT INTO CATEGORY VALUES(10, '상품관련');
INSERT INTO CATEGORY VALUES(20, '주문/결제관련');
INSERT INTO CATEGORY VALUES(30, '반품/환불관련');
INSERT INTO CATEGORY VALUES(40, '회원/정보관련');
INSERT INTO CATEGORY VALUES(50, '기타관련');

-- EVENT 이벤트
CREATE TABLE EVENT(
    EVENT_NO NUMBER PRIMARY KEY,
    EVENT_TITLE VARCHAR2(100) NOT NULL,
    EVENT_WRITER NUMBER NOT NULL,
    COUNT NUMBER DEFAULT 0,
    THUMBNAIL VARCHAR2(100) NOT NULL,
    CONTENT_PHOTO VARCHAR2(100),
    CREATE_DATE DATE DEFAULT SYSDATE,
    START_DATE DATE,
    END_DATE DATE,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
    FOREIGN KEY (EVENT_WRITER) REFERENCES MEMBER(USER_NO)
);

CREATE SEQUENCE SEQ_ENO
NOCACHE;

-- ONE_QNA 1:1문의
CREATE TABLE ONE_QNA(
    ONE_QNA_NO NUMBER PRIMARY KEY,
    CATEGORY_NO NUMBER,
    ONE_QNA_WRITER NUMBER NOT NULL,
    ONE_QNA_TITLE VARCHAR2(100) NOT NULL,
    ONE_QNA_CONTENT VARCHAR2(4000) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    PHONE CHAR(13) NOT NULL,
    ANSWER VARCHAR2(500),
    ANSWER_DATE DATE ,
    ANSWER_YN VARCHAR2(1) DEFAULT 'N' CHECK (ANSWER_YN IN('Y', 'N')),
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
    FOREIGN KEY (ONE_QNA_WRITER) REFERENCES MEMBER(USER_NO),
    FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY(CATEGORY_NO)
);

CREATE SEQUENCE SEQ_ONO
NOCACHE;

-- 게시판 BOARD
CREATE TABLE BOARD(
    BOARD_NO NUMBER PRIMARY KEY,
    BOARD_WRITER NUMBER NOT NULL,
    BOARD_TITLE VARCHAR2(200) NOT NULL,
    BOARD_CONTENT VARCHAR2(4000) NOT NULL,
    BOARD_FILE VARCHAR2(4000),
    CREATE_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y','N')),
    BOARD_TYPE VARCHAR2(16) NOT NULL,
    FOREIGN KEY (BOARD_WRITER) REFERENCES MEMBER(USER_NO)
);
-- BOARD_TYPE 직접 입력(와인용어, 페어링, 매거진)

CREATE SEQUENCE SEQ_BNO
NOCACHE;

-- 문의(0528업데이트)
CREATE TABLE QNA(
  QNA_NO NUMBER PRIMARY KEY,
  PRODUCT_NO NUMBER NOT NULL,
  QNA_WRITER NUMBER NOT NULL,
  QNA_TITLE VARCHAR2(100) NOT NULL,
  QNA_CONTENT VARCHAR2(1000) NOT NULL,
  CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
  COUNT NUMBER DEFAULT 0,
  QNA_OPEN VARCHAR2(10) DEFAULT '공개' CHECK (QNA_OPEN IN('공개', '비공개')),
  ANSWER_YN VARCHAR2(1) DEFAULT 'N' CHECK (ANSWER_YN IN('Y', 'N')),
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
  QNA_PHOTO VARCHAR2(1000),
  ANSWER VARCHAR2(500),
  ANSWER_DATE DATE,
  FOREIGN KEY (QNA_WRITER) REFERENCES MEMBER(USER_NO),
  FOREIGN KEY (PRODUCT_NO) REFERENCES PRODUCT(PRODUCT_NO)
);

CREATE SEQUENCE SEQ_QNO
NOCACHE;

-- 결제
CREATE TABLE PAYMENT_TBL(
    PAYMENT_CODE NUMBER PRIMARY KEY,
    PAYMENT VARCHAR2(15) DEFAULT 'N' NOT NULL
);

-- 픽업장소
CREATE TABLE LOCATION(
    LOCATION_CODE NUMBER PRIMARY KEY,
    LOCATION_NAME VARCHAR2(7)
);


-- 주문 ORDER가 예약어라 못만들어서  W_ORDER로 변경
CREATE TABLE W_ORDER(
    ORDER_NO NUMBER PRIMARY KEY,
    ORDER_USER NUMBER NOT NULL,
    PICKUP VARCHAR2(20) NOT NULL,
    PICKUP_DATE VARCHAR2(20) NOT NULL,
    ORDER_STATUS VARCHAR2(20) DEFAULT '결제완료',
    TOTAL_PRICE NUMBER,
    ORDER_DATE DATE DEFAULT SYSDATE,
    LOCATION_CODE NUMBER NOT NULL,
    PAYMENT_CODE NUMBER NOT NULL,
    FOREIGN KEY (ORDER_USER) REFERENCES MEMBER(USER_NO),
    FOREIGN KEY (LOCATION_CODE) REFERENCES LOCATION(LOCATION_CODE),
    FOREIGN KEY (PAYMENT_CODE) REFERENCES PAYMENT_TBL(PAYMENT_CODE)
    );

CREATE SEQUENCE SEQ_ORDERNO
NOCACHE;

-- 주문_상품 (상품상세보기)
CREATE TABLE ORDER_PRODUCT(
    ORDER_PRODUCT_NO NUMBER PRIMARY KEY,
    ORDER_NO NUMBER,
    PRODUCT_NO NUMBER,
    P_COUNT NUMBER,
    P_PRICE NUMBER,
    FOREIGN KEY (ORDER_NO) REFERENCES W_ORDER(ORDER_NO),
    FOREIGN KEY (PRODUCT_NO) REFERENCES PRODUCT(PRODUCT_NO)    
);

CREATE SEQUENCE SEQ_OPNO
NOCACHE;
    
--상품후기(0525 업데이트)
CREATE TABLE REVIEW(
    REVIEW_NO NUMBER PRIMARY KEY,
    PRODUCT_NO NUMBER NOT NULL,
    REVIEW_WRITER NUMBER NOT NULL,
    ORDER_NO NUMBER NOT NULL,
    REVIEW_TITLE VARCHAR2(100) NOT NULL,
    REVIEW_CONTENT VARCHAR2(1000) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    COUNT NUMBER DEFAULT 0,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    REVIEW_PHOTO VARCHAR2(1000),
    ANSWER VARCHAR2(500),
    ANSWER_DATE DATE,
    ANSWER_YN VARCHAR2(1) DEFAULT 'Y' CHECK (ANSWER_YN IN('Y', 'N')), --(0525업데이트)
    FOREIGN KEY (PRODUCT_NO) REFERENCES PRODUCT(PRODUCT_NO),
    FOREIGN KEY (REVIEW_WRITER) REFERENCES MEMBER(USER_NO),
    FOREIGN KEY (ORDER_NO) REFERENCES W_ORDER(ORDER_NO)
);

CREATE SEQUENCE SEQ_RNO
NOCACHE;

-- CART 카트
CREATE TABLE CART(
    CART_NO NUMBER PRIMARY KEY,
    PRODUCT_NO NUMBER NOT NULL,
    USER_NO NUMBER NOT NULL,
    PRICE NUMBER NOT NULL,
    BOTTLE NUMBER,
    FOREIGN KEY (PRODUCT_NO) REFERENCES PRODUCT(PRODUCT_NO),
    FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO)
);
CREATE SEQUENCE SEQ_CNO
NOCACHE;

---- ATTACHMENT event 로직 변경으로 인해 사용하지 않음.
--CREATE TABLE ATTACHMENT (
--  FILE_NO NUMBER PRIMARY KEY,
--  REF_NO NUMBER NOT NULL,
--  ORIGIN_NAME VARCHAR2(255) NOT NULL,
--  CHANGE_NAME VARCHAR2(255) NOT NULL,
--  FILE_PATH VARCHAR2(1000),
--  UPLOAD_DATE DATE DEFAULT SYSDATE NOT NULL,
--  FILE_LEVEL NUMBER,
--  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
--  FOREIGN KEY (REF_NO) REFERENCES EVENT(EVENT_NO)
--);
--
--CREATE SEQUENCE SEQ_FNO
--NOCACHE;

-- BRATTACHMENT 게시판용 첨부
CREATE TABLE BRATTACHMENT (
  BRFILE_NO NUMBER PRIMARY KEY,
  BRREF_NO NUMBER NOT NULL,
  BRORIGIN_NAME VARCHAR2(255) NOT NULL,
  BRCHANGE_NAME VARCHAR2(255) NOT NULL,
  BRFILE_PATH VARCHAR2(1000),
  BRUPLOAD_DATE DATE DEFAULT SYSDATE NOT NULL,
  BRFILE_LEVEL NUMBER,
  BRSTATUS VARCHAR2(1) DEFAULT 'Y' CHECK(BRSTATUS IN('Y', 'N')),
  FOREIGN KEY (BRREF_NO) REFERENCES BOARD(BOARD_NO)
);

CREATE SEQUENCE SEQ_BRNO
NOCACHE;






COMMIT;


----------------여기서부터 임시 데이터 샘플--------------
------ product 같은 경우는 사용하다가 나중에 엑셀로 넣기 -------
--Insert into WINEFINE.PRODUCT (PRODUCT_NO,PRODUCT_TYPE,PRODUCT_NAME,PRICE,BRAND,ALCOHOL,STOCK,ORIGIN,SWEETNESS,ACIDITY,BODY,TANNIN,STATUS,COUNT,THUMBNAIL,CONTENT_PHOTO1,CONTENT_PHOTO2,CONTENT) values (SEQ_PNO.NEXTVAL,'레드와인','글루미데이',29000,'와인파는청년들',12,100,'한국',3,5,5,5,'Y',0,'/winefine/resources/product_upfiles/2022052322261960731.JPG','/winefine/resources/product_upfiles/2022052409344827765.JPG',null,'null');
--Insert into WINEFINE.PRODUCT (PRODUCT_NO,PRODUCT_TYPE,PRODUCT_NAME,PRICE,BRAND,ALCOHOL,STOCK,ORIGIN,SWEETNESS,ACIDITY,BODY,TANNIN,STATUS,COUNT,THUMBNAIL,CONTENT_PHOTO1,CONTENT_PHOTO2,CONTENT) values (9,'레드와인','콘투고',70000,'안티노리',17,100,'이탈리아',1,1,5,4,'Y',0,'/winefine/resources/product_upfiles/2022052323181093443.JPG','/winefine/resources/product_upfiles/2022052323181097984.JPG','/winefine/resources/product_upfiles/2022052323181070530.JPG',null);
--Insert into WINEFINE.PRODUCT (PRODUCT_NO,PRODUCT_TYPE,PRODUCT_NAME,PRICE,BRAND,ALCOHOL,STOCK,ORIGIN,SWEETNESS,ACIDITY,BODY,TANNIN,STATUS,COUNT,THUMBNAIL,CONTENT_PHOTO1,CONTENT_PHOTO2,CONTENT) values (10,'화이트와인','디오라 샤르도네',39000,'디오라',14, 100,'산타루치아',2,4,4,3,'Y',0,'/winefine/resources/product_upfiles/2022052323260341606.JPG','/winefine/resources/product_upfiles/2022052323260350105.JPG','/winefine/resources/product_upfiles/2022052323260399017.JPG',null);
--Insert into WINEFINE.PRODUCT (PRODUCT_NO,PRODUCT_TYPE,PRODUCT_NAME,PRICE,BRAND,ALCOHOL,STOCK,ORIGIN,SWEETNESS,ACIDITY,BODY,TANNIN,STATUS,COUNT,THUMBNAIL,CONTENT_PHOTO1,CONTENT_PHOTO2,CONTENT) values (8,'레드와인','비냐 조잘 말라예토',35000,'안토니오 산즈',14,100,'스페인',1,4,4,4,'Y',0,'/winefine/resources/product_upfiles/2022052322591961965.JPG','/winefine/resources/product_upfiles/2022052322591986318.JPG','/winefine/resources/product_upfiles/2022052323185436224.JPG','null');

COMMIT;

INSERT INTO LOCATION (LOCATION_CODE, LOCATION_NAME) VALUES (1,'당산');
INSERT INTO LOCATION (LOCATION_CODE, LOCATION_NAME) VALUES (2,'종로');
INSERT INTO LOCATION (LOCATION_CODE, LOCATION_NAME) VALUES (3,'강남');

INSERT INTO PAYMENT_TBL (PAYMENT_CODE,PAYMENT) VALUES (1,'카카오페이');
INSERT INTO PAYMENT_TBL (PAYMENT_CODE,PAYMENT) VALUES (2,'현장결제');

-------- W_order(ORDER_NO 가 있는 테이블)에 아직 샘플 데이터 없어서 현재 오류 ----------

--Insert into WINEFINE.REVIEW (REVIEW_NO,PRODUCT_NO,REVIEW_WRITER,ORDER_NO,REVIEW_TITLE,REVIEW_CONTENT,CREATE_DATE,COUNT,STATUS,REVIEW_PHOTO,ANSWER,ANSWER_DATE) values (SEQ_RNO.NEXTVAL,1,2,1,'만족합니다.','생각보다 맛있어요.',to_date('22/05/22','RR/MM/DD'),16,'Y',null,null,null);
--Insert into WINEFINE.QNA (QNA_NO,PRODUCT_NO,QNA_WRITER,QNA_TITLE,QNA_CONTENT,CREATE_DATE,COUNT,QNA_OPEN,ANSWER_YN,STATUS,QNA_PHOTO,ANSWER,ANSWER_DATE) values (SEQ_QNO.NEXTVAL,1,2,'상품문의','문의드립니다. 와인파인 와인은 뭐가 제일 맛있나요?',to_date('22/05/19','RR/MM/DD'),15,'공개','N','Y',null,null,null);

COMMIT;