CREATE TABLE PRODUCT(
	PRODUCT_NO NUMBER PRIMARY KEY,	
	PRODUCT_TYPE VARCHAR2(30) NOT NULL,
	PRODUCT_NAME VARCHAR2(60) NOT NULL,
	PRICE NUMBER NOT NULL,
	BRAND VARCHAR2(30) NOT NULL,
	ALCOHOL NUMBER NOT NULL,
	STOCK NUMBER NOT NULL,	
	ORIGIN VARCHAR2(30) NOT NULL,
	SWEETNESS NUMBER NOT NULL,
	ACIDITY NUMBER NOT NULL,
	BODY NUMBER NOT NULL,
	TANNIN NUMBER NOT NULL,	
	STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
	COUNT NUMBER DEFAULT 0,	
	THUMBNAIL VARCHAR2(100) NOT NULL,
	CONTENT_PHOTO1 VARCHAR2(100),
	CONTENT_PHOTO2 VARCHAR2(100),
	CONTENT VARCHAR2(4000)
);

INSERT INTO PRODUCT
VALUES(SEQ_PNO.NEXTVAL, '레드', '비냐 조잘 말라예토', 35000, 'VINA ZORZAL WINES,S.A.',
       14.3, 30, '스페인', 1, 4, 4, 4, 'Y', 0, '파일경로', '', '', '');
       
COMMIT;
       
SELECT *
		FROM PRODUCT;