/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-06-07 05:16:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.winefine.order.model.vo.Order;
import com.winefine.common.model.vo.PageInfo;
import com.winefine.member.model.vo.Member;

public final class orderListViewAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/admin/../common/adminHeader.jsp", Long.valueOf(1653847753201L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.winefine.common.model.vo.PageInfo");
    _jspx_imports_classes.add("com.winefine.order.model.vo.Order");
    _jspx_imports_classes.add("com.winefine.member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
 

    ArrayList<Order> oList = (ArrayList<Order>)request.getAttribute("oList");
    PageInfo pi = (PageInfo)request.getAttribute("pi");

    // 페이징바 관련 변수
	int currentPage = pi.getCurrentPage();
	int startPage = pi.getStartPage();
	int endPage = pi.getEndPage();
	int maxPage = pi.getMaxPage();
    

      out.write("   \r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title> WINEFINE :D </title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* 전체 구조 잡기*/\r\n");
      out.write("        div{\r\n");
      out.write("            /* border: 1px solid red;  */\r\n");
      out.write("            /*가이드라인 용이니 다 쓰시고 지우면 됩니다 */\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        .wrap{\r\n");
      out.write("            width: 1200px; \r\n");
      out.write("            height: 800px; \r\n");
      out.write("            margin: auto;\r\n");
      out.write("        }\r\n");
      out.write("        .w_{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .top {\r\n");
      out.write("            height: 240px; /* height: 240px */\r\n");
      out.write("        }\r\n");
      out.write("        .body {\r\n");
      out.write("            height: 600px;\r\n");
      out.write("        }\r\n");
      out.write("        .bottom{\r\n");
      out.write("            height: 100px;  /* height: 100px */\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* 상세 항목 */\r\n");
      out.write("        td{\r\n");
      out.write("            padding-right: 20px;\r\n");
      out.write("            padding-left: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .bottom{\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        .btn{\r\n");
      out.write("        	margin:5px 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #orderList {\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        thead>tr th {\r\n");
      out.write("            padding: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #orderList>tbody>tr td {\r\n");
      out.write("            /* width: 60px; */\r\n");
      out.write("            padding: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* #orderList>tbody>tr:hover {\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            background-color: lightgray;\r\n");
      out.write("            color: rgb(119, 45, 96);\r\n");
      out.write("        } */\r\n");
      out.write("\r\n");
      out.write("        .showDetail:hover {\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            background-color: lightgray;\r\n");
      out.write("            color: rgb(119, 45, 96);\r\n");
      out.write("        }\r\n");
      out.write("        .updateStatus:hover {\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            background-color: lightgray;\r\n");
      out.write("            color: rgb(119, 45, 96);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        /* Modal */\r\n");
      out.write("\r\n");
      out.write("        .modal-content {\r\n");
      out.write("\r\n");
      out.write("            height:auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .modal-body {\r\n");
      out.write("            margin: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("       <!-- top : hearder 삽입 영역 ------------------------------->\r\n");
      out.write("        <div class=\"w_ top\">\r\n");
      out.write("            <div class=\"w_\" style=\"height: 150px;\">\r\n");
      out.write("                <!-- 헤더 START-->\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("\r\n");

    // 메인 화면으로 이동하는 경로 뽑기
    String contextPath = request.getContextPath();

    // 서블릿에서 보낸 메세지 뽑기
	String alertMsg = (String)session.getAttribute("alertMsg");

    Member loginUser = (Member)session.getAttribute("loginUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- * 부트스트랩 영역 --------------------------------------------------------------------------->\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write(" <!-- menubar영역은 모든 페이지마다 넣어주기로 했으니 얘한테 한번 넣어두면 include 되는 모든페이지에서 쓸 수 있겠쥬 ! ☆  -->\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    div {\r\n");
      out.write("        margin: 0px;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        /* 아니 이걸 헤더에다가 넣어두면 안되지1!!!!*/\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .adminHeader{\r\n");
      out.write("        border-collapse: collapse;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .adminHeader td{\r\n");
      out.write("        padding-right: 20px;\r\n");
      out.write("        padding-left: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    #header {\r\n");
      out.write("        background-color: gray;\r\n");
      out.write("    }\r\n");
      out.write("    #header a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: white\r\n");
      out.write("    }\r\n");
      out.write("    #mainlogo {\r\n");
      out.write("        display:inline-block;\r\n");
      out.write("        width: 800px;\r\n");
      out.write("        margin: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    #top_btn button {\r\n");
      out.write("        background-color : rgb(41, 128, 185);\r\n");
      out.write("        color : white;\r\n");
      out.write("        width: 80px;\r\n");
      out.write("        height: 30px;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("    #navigator{\r\n");
      out.write("            \r\n");
      out.write("        background-color: rgb(41, 128, 185);\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("    #navigator label {\r\n");
      out.write("        margin : 10px 30px;\r\n");
      out.write("    }\r\n");
      out.write("    #navigator a {\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-decoration : none;\r\n");
      out.write("        margin:0;\r\n");
      out.write("        text-transform:uppercase; \r\n");
      out.write("        font-size : 18px;\r\n");
      out.write("        font-weight : bold;    \r\n");
      out.write("    }\r\n");
      out.write("    #navigator a:hover {\r\n");
      out.write("        opacity : 0.7;\r\n");
      out.write("    }   \r\n");
      out.write("    .header_r{\r\n");
      out.write("        text-align: right;\r\n");
      out.write("    }\r\n");
      out.write(" \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery-->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- * 부트스트랩 영역 --------------------------------------------------------------------------->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div>\r\n");
      out.write("        <table class=\"adminHeader\">\r\n");
      out.write("            <tr id=\"header\" style=\"height:70%;\">\r\n");
      out.write("                <td style=\"width:800px;\"><a href=\"");
      out.print( contextPath );
      out.write("/main.admin\"><h3 id=\"mainlogo\">ADMINISTRATOR</h3></a></td>\r\n");
      out.write("                <td class=\"header_r\">\r\n");
      out.write("                    <a href=\"");
      out.print( contextPath );
      out.write("/main.do\">Wine Fine&nbsp;</a>\r\n");
      out.write("                    <a href=\"");
      out.print( contextPath );
      out.write("/logout.me\" style=\"color:red\">로그아웃</a>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr id=\"navigator\" style=\"height:30%;\" align=\"center\">\r\n");
      out.write("                <td colspan=\"3\">\r\n");
      out.write("                    <label><a href=\"");
      out.print( contextPath );
      out.write("/memList.me?currentPage=1\">회원정보관리</a></label>\r\n");
      out.write("                    <label><a href=\"");
      out.print( contextPath );
      out.write("/orderListView.admin?currentPage=1\">주문정보관리</a></label>    \r\n");
      out.write("                    <label><a href=\"");
      out.print( contextPath );
      out.write("/productView.admin?currentPage=1\">상품관리</a></label>\r\n");
      out.write("                    <label><a href=\"");
      out.print( contextPath );
      out.write("/list.bo?currentPage=1\">게시판관리</a></label>\r\n");
      out.write("                    <label><a href=\"");
      out.print( contextPath );
      out.write("/Mmain.no\">고객센터관리</a></label>\r\n");
      out.write("                    <label><a href=\"");
      out.print( contextPath );
      out.write("/prepare.do\">통계</a></label>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table> \r\n");
      out.write("           \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    	\r\n");
      out.write("        var message = \"");
      out.print( alertMsg );
      out.write("\";\r\n");
      out.write("        \r\n");
      out.write("        if(message != \"null\") { //로그인 정보가 넘어온 경우\r\n");
      out.write("            \r\n");
      out.write("            alert(message);\r\n");
      out.write("        \r\n");
      out.write("            ");
 session.removeAttribute("alertMsg"); 
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("                <!-- 헤더 END-->\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"w_\" style=\"height: 90px;\">\r\n");
      out.write("           		<br>\r\n");
      out.write("                <table>\r\n");
      out.write("                    <tr id=\"top_btn\">\r\n");
      out.write("                        <td style=\"width:480px; font-size: 22px; font-weight: 600; text-align : left;\">전체 주문 조회</td>\r\n");
      out.write("                        <td colspan=\"2\" style=\"width: 720px; text-align: right;\">\r\n");
      out.write("                            <!-- <button type=\"button\" id=\"insertProduct\">주문수정</button> -->\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td colspan=\"2\"><hr></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- body : 바디 영역 --------------------------------------->\r\n");
      out.write("        <div class=\"w_ body\">\r\n");
      out.write("\r\n");
      out.write("            <br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <table id=\"orderList\" align=\"center\" border=\"1\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>주문번호</th>\r\n");
      out.write("                        <th>주문자</th>\r\n");
      out.write("                        <th>수령인</th>\r\n");
      out.write("                        <th>수령(예정)일</th>\r\n");
      out.write("                        <th>수령지</th>\r\n");
      out.write("                        <th>주문상태</th>\r\n");
      out.write("                        <th>결제금액</th>\r\n");
      out.write("                        <th>주문일</th>\r\n");
      out.write("                        <th>결제방식</th>\r\n");
      out.write("\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("\r\n");
      out.write("                ");
 for( Order o : oList) { 
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                    	<td>");
      out.print( o.getOrderNo() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( o.getOrderUser() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( o.getPickup() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( o.getPickupDate() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( o.getLocationCode() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( o.getOrderStatus() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( o.getTotalPrice() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( o.getOrderDate() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( o.getPaymentCode() );
      out.write("</td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <button type=\"button\" class=\"showDetail\"  data-toggle=\"modal\" data-target=\"#detailOrder\">상세보기</button>\r\n");
      out.write("\r\n");
      out.write("                            ");
 if(o.getOrderStatus().equals("결제대기")) { 
      out.write("\r\n");
      out.write("                                <button type=\"button\" class=\"updateStatus\">결제완료</button>\r\n");
      out.write("                            ");
 } 
                               else if(o.getOrderStatus().equals("결제완료")) { 
      out.write("\r\n");
      out.write("                                <button type=\"button\" class=\"updateStatus\">픽업완료</button>\r\n");
      out.write("                            ");
 }
                               else { 
      out.write("\r\n");
      out.write("                                <button type=\"button\" class=\"updateStatus\">결제대기</button>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("       <!-- bottom : 하단 영역 --------------------------------------->\r\n");
      out.write("       <!-- \r\n");
      out.write("       <div class=\"w_ bottom\" align=\"center\">\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-secondary\">초기화</button>\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-secondary\">수정하기</button>\r\n");
      out.write("       </div>\r\n");
      out.write("       -->\r\n");
      out.write("   \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- The Modal -->\r\n");
      out.write("    <div class=\"modal\" id=\"detailOrder\">\r\n");
      out.write("        <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Modal Header -->\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                <h4 class=\"modal-title\">타이틀</h4>\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Modal body -->\r\n");
      out.write("                <div class=\"modal-body\" align=\"center\">\r\n");
      out.write("                    <!-- <form action=\"\" method=\"post\"> -->\r\n");
      out.write("                        <!-- 현재 비밀번호, 변경할 비밀번호, 변경할 비밀번호 재입력 -->\r\n");
      out.write("                        <input type=\"hidden\" name=\"userId\" value=\"\">\r\n");
      out.write("                        <table style=\"text-align:center;\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr style=\"border-bottom: 1px solid black;\">\r\n");
      out.write("                                    <th>사진</th>\r\n");
      out.write("                                    <th>상품번호</th>\r\n");
      out.write("                                    <th>상품명</th>\r\n");
      out.write("                                    <th>구매수량</th>\r\n");
      out.write("                                    <th>가격</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody id=\"modalTbody\"></tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("\r\n");
      out.write("                        <br>\r\n");
      out.write("\r\n");
      out.write("                        <!-- <button type=\"submit\" class=\"btn btn-secondary btn-sm\" onclick=\"return validatePwd();\">비밀번호 변경</button> -->\r\n");
      out.write("                    <!-- </form> -->\r\n");
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Modal end-->    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 페이징바 -->\r\n");
      out.write("    <div align=\"center\" class=\"paging-area\">\r\n");
      out.write("        	\r\n");
      out.write("        ");
 if(currentPage != 1) { 
      out.write("\r\n");
      out.write("            <button onclick=\"location.href='");
      out.print( contextPath );
      out.write("/orderListView.admin?currentPage=");
      out.print( currentPage - 1 );
      out.write("';\">&lt;</button>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        ");
 for(int p = startPage; p <= endPage; p++) { 
      out.write("\r\n");
      out.write("            ");
 if(p != currentPage) { 
      out.write("\r\n");
      out.write("                <button onclick=\"location.href='");
      out.print( contextPath );
      out.write("/orderListView.admin?currentPage=");
      out.print( p );
      out.write("';\">");
      out.print( p );
      out.write("</button>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                <!-- 현재 내가 보고있는 페이지일 경우는 클릭 안되게끔 -->\r\n");
      out.write("                <button disabled>");
      out.print( p );
      out.write("</button>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        ");
 if(currentPage != maxPage) { 
      out.write("\r\n");
      out.write("            <button onclick=\"location.href='");
      out.print( contextPath );
      out.write("/orderListView.admin?currentPage=");
      out.print( currentPage + 1 );
      out.write("';\">&gt;</button>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <br><br>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        $(function () {\r\n");
      out.write("\r\n");
      out.write("            $(\".showDetail\").click(function () {\r\n");
      out.write("                var orderNo = $(this).parent().parent().children().eq(0).text();\r\n");
      out.write("                \r\n");
      out.write("                console.log(orderNo);\r\n");
      out.write("\r\n");
      out.write("                $.ajax({\r\n");
      out.write("                    url : \"opAjax.admin\",\r\n");
      out.write("                    data : {orderNo : orderNo},\r\n");
      out.write("                    success : function (opList) {\r\n");
      out.write("                        var title = \"주문번호 \" + orderNo + \"번의 상세정보입니다.\";\r\n");
      out.write("                        var content = \"\";\r\n");
      out.write("                        \r\n");
      out.write("                        // console.log(opList);\r\n");
      out.write("\r\n");
      out.write("                        for(var i = 0; i < opList.length; i++) {\r\n");
      out.write("\r\n");
      out.write("                            content += \"<tr>\"\r\n");
      out.write("                                    +            \"<td><img src='\" + opList[i].thumbnail + \"' width='60px'></td>\"\r\n");
      out.write("                                    +            \"<td>\" + opList[i].productNo +\"</td>\"\r\n");
      out.write("                                    +            \"<td>\" + opList[i].productName +\"</td>\"\r\n");
      out.write("                                    +            \"<td>\" + opList[i].pCount + \"병</td>\"\r\n");
      out.write("                                    +             \"<td>\" + opList[i].pPrice + \"원</td>\"\r\n");
      out.write("                                    +      \"</tr>\"\r\n");
      out.write("                                    +      \"<br>\";\r\n");
      out.write("\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        $(\".modal-title\").html(title);\r\n");
      out.write("\r\n");
      out.write("                        $(\"#modalTbody\").html(content);\r\n");
      out.write("\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            $(\".updateStatus\").click(function () {\r\n");
      out.write("                var orderNo = $(this).parent().parent().children().eq(0).text();\r\n");
      out.write("                console.log(orderNo)\r\n");
      out.write("\r\n");
      out.write("                $.ajax({\r\n");
      out.write("                    url : \"orderUpdateAjax.admin\",\r\n");
      out.write("                    data : {orderNo : orderNo},\r\n");
      out.write("                    success : function (o) {\r\n");
      out.write("                        var status = $(this).text()\r\n");
      out.write("\r\n");
      out.write("                        // console.log(result)\r\n");
      out.write("\r\n");
      out.write("                        $(this).parent().parent().children().eq(5).text(o.orderStatus);\r\n");
      out.write("                        // $(\"#orderList\").load(window.location.href + \"orderList\");\r\n");
      out.write("                        location.reload()\r\n");
      out.write("                    }\r\n");
      out.write("                    \r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
