/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-05-26 07:43:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.store;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.winefine.member.model.vo.Member;

public final class viewDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/store/../common/header.jsp", Long.valueOf(1653273810112L));
    _jspx_dependants.put("/views/store/../common/viewDetail-navi.jsp", Long.valueOf(1652595548000L));
    _jspx_dependants.put("/views/store/../common/footer.jsp", Long.valueOf(1652178392000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.winefine.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <link rel=\"styleshhet\" href=\"css/header.css\">\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title> WINEFINE :D </title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* 전체 구조 잡기*/\r\n");
      out.write("        div{\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        .wrap{\r\n");
      out.write("            width:1200px;\r\n");
      out.write("            height: 1500px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("        }\r\n");
      out.write("        .w_{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .top{\r\n");
      out.write("           height: 10%;\r\n");
      out.write("        }\r\n");
      out.write("        .body{\r\n");
      out.write("            height: 70%;\r\n");
      out.write("        }\r\n");
      out.write("        .bottom{\r\n");
      out.write("            height: 300px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* - 구조 : body 영역 _ 4분할 */\r\n");
      out.write("        .body_1{\r\n");
      out.write("            height: 300px;\r\n");
      out.write("        }\r\n");
      out.write("        .body_2{\r\n");
      out.write("            height: 300px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("        /* 테이블 */\r\n");
      out.write("\r\n");
      out.write("        .float{\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("        .float>table{\r\n");
      out.write("            width: 90%;\r\n");
      out.write("        }\r\n");
      out.write("        .summery{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        td{\r\n");
      out.write("            padding:5px;\r\n");
      out.write("            width: 200px;\r\n");
      out.write("        }\r\n");
      out.write("        image{\r\n");
      out.write("            width: 10px;\r\n");
      out.write("            height: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 세부 사항 */\r\n");
      out.write("        .underline{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            border-bottom: 1px solid #BDBDBD;\r\n");
      out.write("        } \r\n");
      out.write("  \r\n");
      out.write("        .body2area{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 180px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("            background-color: #f3f0f0;\r\n");
      out.write("            padding: 30px 100px;\r\n");
      out.write("        }\r\n");
      out.write("        .pairing{\r\n");
      out.write("            background-color: #f3f0f0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 250px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .body_1 a{\r\n");
      out.write("            color:#BDBDBD;\r\n");
      out.write("            font-size: 30px;  \r\n");
      out.write("            text-decoration: none; \r\n");
      out.write("        }\r\n");
      out.write("        .body_1 .btn{\r\n");
      out.write("            border: none;\r\n");
      out.write("            width: 240px;\r\n");
      out.write("            margin-left: 10px;\r\n");
      out.write("            margin-top: 0px;\r\n");
      out.write("        }\r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("   <div class=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("        <!-- top : hearder 삽입 영역 ------------------------------->\r\n");
      out.write("        <div class=\"w_ top\">\r\n");
      out.write("\r\n");
      out.write("            <!-- 헤더 START-->\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("\r\n");
 
	// 로그인한 사용자 정보 뽑기
	Member loginUser = (Member)session.getAttribute("loginUser"); 
	// 서블릿에서 보낸 메세지 뽑기
	String alertMsg = (String)session.getAttribute("alertMsg");
	// 메인 화면으로 이동하는 경로 뽑기
	String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title> WINEFINE :D </title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- * 부트스트랩 영역 --------------------------------------------------------------------------->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write(" <!-- menubar영역은 모든 페이지마다 넣어주기로 했으니 얘한테 한번 넣어두면 include 되는 모든페이지에서 쓸 수 있겠쥬 ! ☆  -->\r\n");
      out.write("\r\n");
      out.write("<!-- swiper.js -->\r\n");
      out.write("<link\r\n");
      out.write("  rel=\"stylesheet\"\r\n");
      out.write("  href=\"https://unpkg.com/swiper@8/swiper-bundle.min.css\"\r\n");
      out.write("/>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://unpkg.com/swiper@8/swiper-bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .logo {\r\n");
      out.write("        width: 400px;\r\n");
      out.write("        float: left;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .logo>a {\r\n");
      out.write("        margin-left: 50px; /* 로고의 왼쪽 여백 설정 */\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .top_right_menu { float: right;}\r\n");
      out.write("\r\n");
      out.write("    .top_right_menu li{\r\n");
      out.write("        list-style-type: none;\r\n");
      out.write("        float: left;\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("        padding-right: 10px;\r\n");
      out.write("        padding-left: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    #top_service>a { margin-right: 50px;} /* 우측 상단 아이콘의 오른쪽 여백 설정 */\r\n");
      out.write("\r\n");
      out.write("    .menu {\r\n");
      out.write("        display: table-cell;\r\n");
      out.write("        height: 50px;\r\n");
      out.write("        width: 200px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: black;\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        display: block; \r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        line-height: 50px; /* 장평조절: 위~ 아래에서 가운데 조정 */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu a:hover {\r\n");
      out.write("        color:#6B325B;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu:after {\r\n");
      out.write("            display:block;\r\n");
      out.write("            content: '';\r\n");
      out.write("            border-bottom: solid 5px #6B325B;  \r\n");
      out.write("            transform: scaleX(0);  \r\n");
      out.write("            transition: transform 250ms ease-in-out;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu:hover:after { transform: scaleX(0.6); }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"top\" >\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <a href=\"");
      out.print( contextPath );
      out.write("/main.do\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/winefine_logo.png\" width=\"250px\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul class=\"top_right_menu\">\r\n");
      out.write("            <li id=\"top_search\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/icon_search.png\" class=\"btn\" data-toggle=\"modal\" data-target=\"#searchModal\"\r\n");
      out.write("                style=\"padding:0px\"></li>\r\n");
      out.write("            ");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("                <li id=\"top_cart\"><a href=\"");
      out.print( contextPath );
      out.write("/loginForm.me\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/icon_cart.png\"></a></li>\r\n");
      out.write("            ");
 }
               else { 
      out.write("\r\n");
      out.write("                <li id=\"top_cart\"><a href=\"");
      out.print( contextPath );
      out.write("/cart.me\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/icon_cart.png\"></a></li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <!-- 로그인 된 상태가 아니라면 보일것-->\r\n");
      out.write("            ");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("            	<li id=\"top_mypage\"><a href=\"");
      out.print( contextPath );
      out.write("/loginForm.me\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/icon_mypage.png\"></a></li>\r\n");
      out.write("            ");
 }
               else if(!loginUser.getUserId().equals("admin")) { 
      out.write("\r\n");
      out.write("	            <!-- 로그인한 사람이 admin이 아니라면 보일것-->\r\n");
      out.write("	            <li id=\"top_mypage\"><a href=\"");
      out.print( contextPath );
      out.write("/myPage.me\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/icon_mypage.png\"></a></li>\r\n");
      out.write("	        ");
 }
               else { 
      out.write("\r\n");
      out.write("	            <!-- 만약 로그인한 사람이 admin이라면 보일것 -->\r\n");
      out.write("	            <li id=\"top_mypage\"><a href=\"");
      out.print( contextPath );
      out.write("/views/admin/adminMain.jsp\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/icon_mypage.png\"></a></li>\r\n");
      out.write("	        ");
 } 
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <li id=\"top_service\"><a href=\"");
      out.print( contextPath );
      out.write("/list.no\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/icon_center.png\"></a></li>\r\n");
      out.write("            <li><a href=\"");
      out.print( contextPath );
      out.write("/logout.me\">로그아웃</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <br clear=\"both\">\r\n");
      out.write("    <br>\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("    <div class=\"nav-area\" align=\"center\">\r\n");
      out.write("        <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/views/store/viewAll.jsp\">와인스토어</a></div>\r\n");
      out.write("        <div class=\"menu\"><a href=\"\">소울와인찾기</a></div>\r\n");
      out.write("        <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/views/board/terminologyAll.jsp\">게시판</a></div>\r\n");
      out.write("        <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.no\">고객센터</a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- The Modal -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"searchModal\" style=\"background-color: white; \">\r\n");
      out.write("        <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("        <div class=\"modal-content\" style=\"border-color: white;\">\r\n");
      out.write("        \r\n");
      out.write("            <!-- Modal Header -->\r\n");
      out.write("            <div class=\"modal-header\" style=\"border-color: white;\">\r\n");
      out.write("            <h4 class=\"modal-title\"></h4>\r\n");
      out.write("            <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Modal body -->\r\n");
      out.write("            <form>\r\n");
      out.write("                <div class=\"modal-body\" style=\"width:1200px; height: 400px; border-color: white;\">\r\n");
      out.write("                    <b style=\"font-size: 100px;\">search</b><br>\r\n");
      out.write("                    <input type=\"text\" name=\"searchWord\" placeholder=\"원하시는 검색어를 입력하세요.\"\r\n");
      out.write("                        style=\"font-size: 50px; color:grey; width: 1000px; height: 100px; border: white;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Modal footer -->\r\n");
      out.write("                <div class=\"modal-footer\" style=\"border-color: white;\">\r\n");
      out.write("                        <input type=\"submit\" class=\"btn btn-secondary\" value=\"검색하기\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    	\r\n");
      out.write("        var message = \"");
      out.print( alertMsg );
      out.write("\";\r\n");
      out.write("        \r\n");
      out.write("        if(message != \"null\") { //로그인 정보가 넘어온 경우\r\n");
      out.write("            \r\n");
      out.write("            alert(message);\r\n");
      out.write("        \r\n");
      out.write("            ");
 session.removeAttribute("alertMsg"); 
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("            <!-- 헤더 END-->\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("       <!-- body : 카테고리 페이지 바디 영역 --------------------------------------------->\r\n");
      out.write("       <div class=\"w_ body\">\r\n");
      out.write("\r\n");
      out.write("            <!-- body1 : 상품이미지 & 상품명 -->\r\n");
      out.write("            <div class=\"w_ body_1\" >\r\n");
      out.write("                <div class=\"float\" style=\"width: 45%; padding-left: 150px;\" >\r\n");
      out.write("                    <img src=\"../../resources/images/producdEx.JPG\" style=\"height: 300px;\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"float\" style=\"width: 55%; padding: 20px;\">\r\n");
      out.write("                    <table align=\"center;\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td style=\"border-bottom: 1px solid #BDBDBD; font-size: 12px;\">상위카테고리 > 하위카테고리 > 상품명</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><br><h2>상품명</h2></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>");
      out.print( p.getProductName );
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td style=\"text-align: center;\"><h4>29000원</h4></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td style=\"border-bottom: 1px solid #BDBDBD;\">도수 12.5 %<br><br></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        \r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("\r\n");
      out.write("                                \r\n");
      out.write("                                &nbsp;&nbsp;\r\n");
      out.write("                                <input type=\"button\" class=\"btn btn-secondary\" style=\"background-color: #BDBDBD;\" value=\"장바구니\"\r\n");
      out.write("                                data-toggle=\"modal\" data-target=\"#myModal\">\r\n");
      out.write("                                \r\n");
      out.write("                                    <!-- 장바구니 모달 영역 START -->\r\n");
      out.write("                                    <div class=\"modal fade\" id=\"myModal\">\r\n");
      out.write("                                        <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("                                        <div class=\"modal-content\">\r\n");
      out.write("                                        \r\n");
      out.write("                                            <!-- Modal Header -->\r\n");
      out.write("                                            <div class=\"modal-header\" style=\"background-color: #f3f0f0;\">\r\n");
      out.write("                                                <b class=\"modal-title\" style=\"font-size: 22px;\">와인파인와인이름</b>\r\n");
      out.write("                                                <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            \r\n");
      out.write("                                            <form>\r\n");
      out.write("                                            <!-- Modal body -->\r\n");
      out.write("                                            <div class=\"modal-body\" style=\"background-color: #f3f0f0;\">\r\n");
      out.write("                                                <table align=\"center\">\r\n");
      out.write("                                                    <tr>\r\n");
      out.write("                                                        <td>\r\n");
      out.write("                                                            WINE FINE WINE NAME\r\n");
      out.write("                                                        </td>\r\n");
      out.write("                                                        <td>\r\n");
      out.write("                                                            <input type=\"number\" min=\"0\" required; placeholder=\"1\">\r\n");
      out.write("                                                        </td>\r\n");
      out.write("                                                        <td>\r\n");
      out.write("                                                            <b> 누적금액 xxx,xxx원 </b>\r\n");
      out.write("                                                        </td>\r\n");
      out.write("                                                    </tr>\r\n");
      out.write("                                                </table>\r\n");
      out.write("                                                <br><br><br><br><br><br><br><br>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            \r\n");
      out.write("                                            <!-- Modal footer -->\r\n");
      out.write("                                            <div class=\"modal-footer\" style=\"background-color: #f3f0f0;\">\r\n");
      out.write("                                                <table>\r\n");
      out.write("                                                    <tr>\r\n");
      out.write("                                                        <td>\r\n");
      out.write("                                                            <input type=\"button\" class=\"btn btn-secondary\" style=\"background-color: #BDBDBD;\" value=\"← 돌아가기\">\r\n");
      out.write("                                                        </td>\r\n");
      out.write("                                                        <td>\r\n");
      out.write("                                                            <input type=\"submit\" class=\"btn btn-secondary\" style=\"background-color: #6B325B;\" value=\"바로 구매하기\">\r\n");
      out.write("                                                        </td>\r\n");
      out.write("                                                    </tr>\r\n");
      out.write("                                                </table>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            </form>\r\n");
      out.write("                                            \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- 장바구니 모달 영역 END-->\r\n");
      out.write("\r\n");
      out.write("                                <input type=\"button\" class=\"btn btn-secondary\" style=\"background-color: #6B325B;\" value=\"구매하기\">\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br clear=\"both\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- body2 : 상품 요약 정보 -->\r\n");
      out.write("            <div class=\"w_ body_2\">\r\n");
      out.write("                <div class=\"underline\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"body2area\">\r\n");
      out.write("                    <table class=\"summery\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><li>생산지역</li></td>\r\n");
      out.write("                            <td></td>\r\n");
      out.write("\r\n");
      out.write("                            <td><li>당도</li></td>\r\n");
      out.write("                            <td></td>\r\n");
      out.write("\r\n");
      out.write("                            <td rowspan=\"3\">\r\n");
      out.write("                                <img src=\"../../resources/images/vivino-logo.png\">\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><li>와이너리</li></td>\r\n");
      out.write("                            <td></td>\r\n");
      out.write("\r\n");
      out.write("                            <td><li>당도</li></td>\r\n");
      out.write("                            <td></td>\r\n");
      out.write("\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td><li>와인도수</li></td>\r\n");
      out.write("                            <td></td>\r\n");
      out.write("\r\n");
      out.write("                            <td><li>바디</li></td>\r\n");
      out.write("                            <td></td>\r\n");
      out.write("\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td></td>\r\n");
      out.write("                            <td></td>\r\n");
      out.write("\r\n");
      out.write("                            <td><li>탄닌</li></td>\r\n");
      out.write("                            <td></td>\r\n");
      out.write("                            <td>&nbsp;&nbsp;출처 : 비비노</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("\r\n");
      out.write("            <!-- body2 : 함께하면 좋은 음식(페어링)-->\r\n");
      out.write("            <div class=\"w_ body_2\">\r\n");
      out.write("                <div class=\"underline\">\r\n");
      out.write("                    <b style=\"font-size:20px;\">&nbsp;함께하면 좋은 음식</b>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <table class=\"pairing\">\r\n");
      out.write("                        <td>\r\n");
      out.write("                         </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>\r\n");
      out.write("\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- body3: 상세페이지-->\r\n");
      out.write("            <div class=\"w_ body_3\">\r\n");
      out.write("                <div class=\"underline\" >\r\n");
      out.write("                </div><br>\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("                    <!-- viewDetail-navi 영역 START -->\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("        /* viewDetail-navi 세부사항 */\r\n");
      out.write("        #viewDetail-navi a{\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: white;\r\n");
      out.write("        display: block;\r\n");
      out.write("        }\r\n");
      out.write("        #viewDetail-navi{\r\n");
      out.write("            width:1200px;\r\n");
      out.write("            margin : 0px;\r\n");
      out.write("            padding :0px;\r\n");
      out.write("        }\r\n");
      out.write("        #viewDetail-navi > li{\r\n");
      out.write("            width: 20%;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            line-height: 25px;\r\n");
      out.write("            background-color: black;\r\n");
      out.write("            border: 1px solid white;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            float: left;\r\n");
      out.write("            list-style-type : none;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        #viewDetail-navi > li :hover{\r\n");
      out.write("            display: block;\r\n");
      out.write("            background-color: #6B325B;\r\n");
      out.write("        }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <ul id=\"viewDetail-navi\">\r\n");
      out.write("        <li><a href=\"../store/viewDetail1.jsp\">상세페이지</a></li>\r\n");
      out.write("        <li><a href=\"../store/viewDetail2.jsp\">상품정보</a></li>\r\n");
      out.write("        <li><a href=\"../store/viewDetail3.jsp\">교환 및 반품 안내</a></li>\r\n");
      out.write("        <li><a href=\"../store/viewDetail4.jsp\">상품후기</a></li>\r\n");
      out.write("        <li><a href=\"../store/viewDetail5.jsp\">Q & A</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    <br clear=\"both\">\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("                    <!-- viewDetail-navi 영역 END-->\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("                    <!-- viewDetail-content 영역-->\r\n");
      out.write("                    <div class=\"pairing\" style=\"height: 1000px;\">\r\n");
      out.write("                        여기에 상세설명\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <br><br>\r\n");
      out.write("            \r\n");
      out.write("            <!-- bottom : 푸터바 영역 ---------------------------------------------------->\r\n");
      out.write("            <div class=\"w_ bottom\">\r\n");
      out.write("            <!-- 푸터바 START-->\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title> WINEFINE :D </title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* 가이드라인*/\r\n");
      out.write("        div,table{\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        body, p{\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* 구조잡기*/\r\n");
      out.write("        .bottom{\r\n");
      out.write("            width: 1200px;\r\n");
      out.write("            /* 전체 height 1500px의 20%로 가정*/\r\n");
      out.write("            height: 300px;\r\n");
      out.write("            margin:auto;\r\n");
      out.write("        }\r\n");
      out.write("        .footer1, .footer3{\r\n");
      out.write("            width: 1200px;\r\n");
      out.write("            height: 15%;\r\n");
      out.write("        }\r\n");
      out.write("        .footer2{\r\n");
      out.write("            width: 1200px;\r\n");
      out.write("            height: 70%;\r\n");
      out.write("        }\r\n");
      out.write("        .left, .right{\r\n");
      out.write("            width: 25%;\r\n");
      out.write("            vertical-align: middle;\r\n");
      out.write("        }\r\n");
      out.write("        .center{\r\n");
      out.write("            width:50%;\r\n");
      out.write("        }\r\n");
      out.write("        #table{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 세부 사항 */\r\n");
      out.write("        .footer{\r\n");
      out.write("            background-color: black;\r\n");
      out.write("            border-bottom: 1px solid gray;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .table{\r\n");
      out.write("            color:grey;\r\n");
      out.write("        }\r\n");
      out.write("        .footer1{\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        .footer1, .footer3{\r\n");
      out.write("            line-height: 40px;\r\n");
      out.write("        }\r\n");
      out.write("        .text{\r\n");
      out.write("            color:white;\r\n");
      out.write("        }\r\n");
      out.write("        a{\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("        a:hover{\r\n");
      out.write("            color: gray;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("        #logo{\r\n");
      out.write("            color: #6B325B;\r\n");
      out.write("        }\r\n");
      out.write("        .center, #copyright{\r\n");
      out.write("            font-size: 80%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- 모든페이지 > bottom 영역에 들어갈 푸터바         -->\r\n");
      out.write("    <!-- 참고) 푸터바 영역은 전체 height:1500px의 20% 할당-->\r\n");
      out.write("    <div class=\"bottom\">\r\n");
      out.write("        <div class=\"footer footer1\">\r\n");
      out.write("            <span class=\"text\"><a href=\"\">브랜드소개</a> &nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp; </span>\r\n");
      out.write("            <span class=\"text\"><a href=\"\">오시는 길</a> &nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp; </span>  \r\n");
      out.write("            <span class=\"text\"><a href=\"\">이용약관</a> &nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp; </span> \r\n");
      out.write("            <span class=\"text\"><a href=\"\">개인정보취급방침</a> &nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp; </span> \r\n");
      out.write("            <span class=\"text\"><a href=\"\">고객센터</a> </span> \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer footer2\">\r\n");
      out.write("            <table id=\"table\">\r\n");
      out.write("                <td class=\"left\">\r\n");
      out.write("                    <h1 id=\"logo\">WINEFINE</h1>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td class=\"table center\">\r\n");
      out.write("                    (주)와인파인 대표자: WINEFINE<br>\r\n");
      out.write("                    사업자등록번호: [KH-452-02-00843] 통신판매업자신고번호: 제2022-서울 영등포 - NO4호<br>\r\n");
      out.write("                    대표번호: KH-1640-5091 주소: 서울특별시 영등포구 선유동2로 57 이레빌딩 19F, 20F<br>\r\n");
      out.write("                    개인정보관리자: KH(khlove@iei.co.kr)<br>\r\n");
      out.write("                    대표메일 winefine@iei.co.kr 사이트명: 와인파인<br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    Bank Accounts : KH은행 027-142321-01-004 주식회사 와인파인<br>\r\n");
      out.write("                    CS Center : 1661-5091 AM 10:00 ~ PM 6:00<br>\r\n");
      out.write("                    (점심시간 PM 1:00~ 2:00) ( WEEKEND/HOLIDAY OFF )<br>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td class=\"table right\">\r\n");
      out.write("                    <h5>고객센터 운영시간</h5>\r\n");
      out.write("                    평일 10:00 - 18:00<br>\r\n");
      out.write("                    점심시간 13:00 - 14:00<br>\r\n");
      out.write("                    주말 및 공휴일 휴무\r\n");
      out.write("                </td>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("            \r\n");
      out.write("        <div class=\"footer footer3\">\r\n");
      out.write("            <p id =\"copyright\" class=\"text\">Copyright © 2022 WINEFINE Information All Right Reserved</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("            <!-- 푸터바 END-->\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("       </div>\r\n");
      out.write("   </div> \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
