/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-05-18 14:23:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.notice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contactUsView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/notice/../common/menubar2.jsp", Long.valueOf(1652883380107L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("        .outer{\r\n");
      out.write("            width: 1000px;\r\n");
      out.write("            height: 700px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            margin: 50px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .tabcontent {\r\n");
      out.write("            display : none;\r\n");
      out.write("        }\r\n");
      out.write("        #tab, .tabcontent { width : 100%; }\r\n");
      out.write("        .tablinks {\r\n");
      out.write("            background-color: rgb(107, 50, 91);\r\n");
      out.write("            color: white;\r\n");
      out.write("            width: 150px;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        .tablinks:hover {\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            opacity : 0.7;\r\n");
      out.write("        }\r\n");
      out.write("       \r\n");
      out.write("    \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("        div {\r\n");
      out.write("            box-sizing : border-box;\r\n");
      out.write("            border : 1px solid red;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .wrap {\r\n");
      out.write("            width : 1000px;\r\n");
      out.write("            height : 800px;\r\n");
      out.write("            margin : auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 크게 세가지 영역 */\r\n");
      out.write("        .wrap>div {\r\n");
      out.write("            width : 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #header, #footer {\r\n");
      out.write("            height : 20%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #navigator{\r\n");
      out.write("            height : 5%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #content {\r\n");
      out.write("            height : 55%\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* header 의 두가지 영역 */\r\n");
      out.write("        #header>div, #content>div {\r\n");
      out.write("            height : 100%;\r\n");
      out.write("            float : left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #header_1, #header_{\r\n");
      out.write("            width : 20%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #header_2 {\r\n");
      out.write("            width : 60%;\r\n");
      out.write("        }\r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("        #content_1 {\r\n");
      out.write("            width : 20%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #content_2 {\r\n");
      out.write("            width : 80%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 메뉴바 */\r\n");
      out.write("\r\n");
      out.write("        #navi {\r\n");
      out.write("            list-style-type : none;\r\n");
      out.write("            margin : 0px;\r\n");
      out.write("            padding : 0px;\r\n");
      out.write("            height : 100%;\r\n");
      out.write("    \r\n");
      out.write("        }\r\n");
      out.write("        #navi li {\r\n");
      out.write("            float : left;\r\n");
      out.write("            width : 25%;\r\n");
      out.write("            height : 100%;\r\n");
      out.write("            text-align : center;\r\n");
      out.write("        }\r\n");
      out.write("        .menu a {\r\n");
      out.write("            color: #000;\r\n");
      out.write("            text-decoration : none;\r\n");
      out.write("            margin:0;\r\n");
      out.write("            text-transform:uppercase; \r\n");
      out.write("            font-size : 20px;\r\n");
      out.write("            font-weight : bold;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("    \r\n");
      out.write("        .menu:after {\r\n");
      out.write("            display:block;\r\n");
      out.write("            content: '';\r\n");
      out.write("            border-bottom: solid 5px rgb(107, 50, 91);  \r\n");
      out.write("            transform: scaleX(0);  \r\n");
      out.write("            transition: transform 250ms ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("        .menu:hover:after { transform: scaleX(0.5); }\r\n");
      out.write("\r\n");
      out.write("        /* 왼쪽 메뉴바 */\r\n");
      out.write("\r\n");
      out.write("        #leftNavi {\r\n");
      out.write("            list-style-type : none;\r\n");
      out.write("            margin : 0px;\r\n");
      out.write("            padding : 0px;\r\n");
      out.write("            height : 100%;\r\n");
      out.write("    \r\n");
      out.write("        }\r\n");
      out.write("        #leftNavi li {\r\n");
      out.write("            width : 100%;\r\n");
      out.write("            height : 11%;\r\n");
      out.write("            text-align : center;\r\n");
      out.write("        }\r\n");
      out.write("        .left_menu a {\r\n");
      out.write("            color: #000;\r\n");
      out.write("            text-decoration : none;\r\n");
      out.write("            margin:0;\r\n");
      out.write("            text-transform:uppercase; \r\n");
      out.write("            font-size : 20px;\r\n");
      out.write("            font-weight : bold;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("    \r\n");
      out.write("        .left_menu:after {\r\n");
      out.write("            display:block;\r\n");
      out.write("            content: '';\r\n");
      out.write("            border-bottom: solid 3px rgb(107, 50, 91);  \r\n");
      out.write("            transform: scaleX(0);  \r\n");
      out.write("            transition: transform 250ms ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("        .left_menu:hover:after { transform: scaleX(0.5); }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("        <div id=\"header\">\r\n");
      out.write("            <div id=\"header_1\">\r\n");
      out.write("                <img src=>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"header_2\"></div>\r\n");
      out.write("            <div id=\"header_3\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"navigator\">\r\n");
      out.write("        <ul id=\"navi\">\r\n");
      out.write("            <li class=\"menu\"><a href=\"\">와인스토어</a></li>\r\n");
      out.write("            <li class=\"menu\"><a href=\"\">소울와인 찾기</a></li>\r\n");
      out.write("            <li class=\"menu\"><a href=\"\">게시판</a></li>\r\n");
      out.write("            <li class=\"menu\"><a href=\"/winefine/list.no\">고객센터</a></li>\r\n");
      out.write("        </ul>   \r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"content\">\r\n");
      out.write("            <div id=\"content_1\">\r\n");
      out.write("                <ul id=\"leftNavi\">\r\n");
      out.write("                    <h1 align=\"center\">고객센터</h1>\r\n");
      out.write("                    <hr style=\"border: 1px solid black\">\r\n");
      out.write("                    <li class=\"left_menu\"><a href=\"/winefine/list.no\">공지사항</a></li><hr>\r\n");
      out.write("                    <li class=\"left_menu\"><a href=\"/winefine/list.ev\">이벤트</a></li><hr>\r\n");
      out.write("                    <li class=\"left_menu\"><a href=\"/winefine/list.on\">1:1문의</a></li><hr>\r\n");
      out.write("                    <li class=\"left_menu\"><a href=\"/winefine/list.co\">Contact Us</a></li><hr>\r\n");
      out.write("                    <li class=\"left_menu\"><a href=\"/winefine/list.fa\">FAQ</a></li>\r\n");
      out.write("                </ul> \r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"content_2\"></div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"footer\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"outer\">\r\n");
      out.write("\r\n");
      out.write("        <br>\r\n");
      out.write("        <h2 align=\"center\">ContactUs</h2>\r\n");
      out.write("        <br>\r\n");
      out.write("        <hr style=\"border: 1px solid black\" width=\"750\">\r\n");
      out.write("        <br>\r\n");
      out.write("        <div id=\"contactUs-form\">\r\n");
      out.write("            <table align=\"center\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"2\">\r\n");
      out.write("                        <h2>WINE FINE 매장안내</h2><br>\r\n");
      out.write("                    와인이 필요한 순간에, 가장 가까운 와인나라 매장을 찾아주세요!<br>\r\n");
      out.write("                    3개 직영매장 (당산점 / 종로점 / 강남점 ) 및 입점매장으로 운영됩니다.\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"2\">\r\n");
      out.write("                        <div id=\"tab\">\r\n");
      out.write("                        <button class=\"tablinks\">당산점</button>\r\n");
      out.write("                        <button class=\"tablinks\">종로점</button>\r\n");
      out.write("                        <button class=\"tablinks\">강남점</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </td>   \r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            <br><br>\r\n");
      out.write("            <table id=\"dang\" class=\"tabcontent\" align=\"center\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <img src=\"\" alt=\"\" name=\"dangImg\" width=\"500\" height=\"350\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td width=\"500\">\r\n");
      out.write("                        <h2>WINE FINE 당산점</h2>\r\n");
      out.write("                        <img src=\"\">매장 위치 <br>\r\n");
      out.write("                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~<br>\r\n");
      out.write("                        <img src=\"\"> 영업 시간 <br>\r\n");
      out.write("                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~<br>\r\n");
      out.write("                        <img src=\"\"> 매장 번호<br>\r\n");
      out.write("                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"2\">\r\n");
      out.write("                        <img src=\"\" name=\"kakao_dang\" width=\"100%\" height=\"300\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"3\">\r\n");
      out.write("                        대중교통<br>\r\n");
      out.write("                        - 지하철 9호선 국회의사당역 1번 출구 도보 5분\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <table id=\"jong\" class=\"tabcontent\" align=\"center\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <img src=\"\" alt=\"\" name=\"jongImg\" width=\"500\" height=\"350\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td width=\"500\">\r\n");
      out.write("                        <h2>WINE FINE 종로점</h2>\r\n");
      out.write("                        <img src=\"\">매장 위치 <br>\r\n");
      out.write("                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~<br>\r\n");
      out.write("                        <img src=\"\"> 영업 시간 <br>\r\n");
      out.write("                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~<br>\r\n");
      out.write("                        <img src=\"\"> 매장 번호<br>\r\n");
      out.write("                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"2\">\r\n");
      out.write("                        <img src=\"\" name=\"kakao_jong\" width=\"100%\" height=\"300\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"3\">\r\n");
      out.write("                        대중교통<br>\r\n");
      out.write("                        - 지하철 9호선 국회의사당역 1번 출구 도보 5분\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("\r\n");
      out.write("            <table id=\"kang\" class=\"tabcontent\" align=\"center\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <img src=\"\" alt=\"\" name=\"kang\" width=\"500\" height=\"350\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td width=\"500\">\r\n");
      out.write("                        <h2>WINE FINE 강남점</h2>\r\n");
      out.write("                        <img src=\"\">매장 위치 <br>\r\n");
      out.write("                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~<br>\r\n");
      out.write("                        <img src=\"\"> 영업 시간 <br>\r\n");
      out.write("                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~<br>\r\n");
      out.write("                        <img src=\"\"> 매장 번호<br>\r\n");
      out.write("                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"2\">\r\n");
      out.write("                        <img src=\"\" name=\"kakao_kang\" width=\"100%\" height=\"300\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"3\">\r\n");
      out.write("                        대중교통<br>\r\n");
      out.write("                        - 지하철 9호선 국회의사당역 1번 출구 도보 5분\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            $(function() {\r\n");
      out.write("                $(\".tablinks\").click(function() {\r\n");
      out.write("\r\n");
      out.write("                    $(\".tablinks\").css({backgroundColor : \"\", border : \"\"});\r\n");
      out.write("        \r\n");
      out.write("                    $(\".tabcontent\").css(\"display\", \"\");\r\n");
      out.write("\r\n");
      out.write("                    var city = $(this).text();\r\n");
      out.write("\r\n");
      out.write("                    if(city == \"당산점\") {\r\n");
      out.write("        \r\n");
      out.write("                         $(\"#dang\").css(\"display\", \"block\");\r\n");
      out.write("\r\n");
      out.write("                     }\r\n");
      out.write("\r\n");
      out.write("                    else if(city == \"종로점\") {\r\n");
      out.write("\r\n");
      out.write("                        $(\"#jong\").css(\"display\", \"block\");\r\n");
      out.write("\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    else {\r\n");
      out.write("\r\n");
      out.write("                        $(\"#kang\").css(\"display\", \"block\");\r\n");
      out.write("\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
