/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-05-23 12:02:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title> WINEFINE :D </title>\r\n");
      out.write("    <style>\r\n");
      out.write("            /* 기본세팅 */\r\n");
      out.write("            div{\r\n");
      out.write("                color: white;\r\n");
      out.write("            }\r\n");
      out.write("            h1,p{\r\n");
      out.write("                margin: 0;\r\n");
      out.write("            }\r\n");
      out.write("            body{\r\n");
      out.write("                background-size: cover;   /* 이미지 사이즈 꽉 차게*/\r\n");
      out.write("                background-image: url(\"/winefine/resources/images/enter_cut.jpg\");\r\n");
      out.write("                background-repeat: no-repeat; /* 이미지 반복 */\r\n");
      out.write("                background-color: #6B325B;\r\n");
      out.write("            } \r\n");
      out.write("            \r\n");
      out.write("            /* 전체구조 */\r\n");
      out.write("            .wrap{\r\n");
      out.write("                width: 1200px; \r\n");
      out.write("                height: 730px; \r\n");
      out.write("                margin: auto;\r\n");
      out.write("            } \r\n");
      out.write("            .top{\r\n");
      out.write("                height: 35%;\r\n");
      out.write("            }\r\n");
      out.write("            .body{\r\n");
      out.write("                height: 8%;\r\n");
      out.write("            }\r\n");
      out.write("            .bottom{\r\n");
      out.write("                height: 31%;\r\n");
      out.write("            }\r\n");
      out.write("            input{\r\n");
      out.write("                width: 7%;\r\n");
      out.write("                height: 50px;\r\n");
      out.write("                font-size:150%;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("    \r\n");
      out.write("            /* 세부사항 */\r\n");
      out.write("            a{\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("                color: white;\r\n");
      out.write("            }\r\n");
      out.write("            a:hover{\r\n");
      out.write("                color: white;            \r\n");
      out.write("            }\r\n");
      out.write("            .w_ {\r\n");
      out.write("                text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("            .top{\r\n");
      out.write("                line-height: 500px;\r\n");
      out.write("                font-weight: 900;\r\n");
      out.write("                font-size: xx-large;\r\n");
      out.write("            }\r\n");
      out.write("            .text{\r\n");
      out.write("                font-size:14px;\r\n");
      out.write("            }\r\n");
      out.write("            .btn{\r\n");
      out.write("                width: 200px;\r\n");
      out.write("                height: 45px;\r\n");
      out.write("                font-size: 20px;\r\n");
      out.write("    			font-weight: 600;\r\n");
      out.write("                border-radius: 50px;\r\n");
      out.write("                border: 1px solid #6B325B;\r\n");
      out.write("                background-color: #6B325B;\r\n");
      out.write("            }\r\n");
      out.write("            .btn:hover{\r\n");
      out.write("                color: white;\r\n");
      out.write("                background-color: black;\r\n");
      out.write("                border: 1px solid black;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("            }\r\n");
      out.write("    \r\n");
      out.write("            #description1{\r\n");
      out.write("                font-size: 25px;\r\n");
      out.write("                line-height: 70px;\r\n");
      out.write("            }\r\n");
      out.write("            #description2{\r\n");
      out.write("                line-height: 80px;\r\n");
      out.write("            }\r\n");
      out.write("            #description3{\r\n");
      out.write("                padding: 1%;\r\n");
      out.write("                font-weight: 600;\r\n");
      out.write("                color: #6B325B;\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"wrap\">\r\n");
      out.write("                <div class=\"w_ top\">\r\n");
      out.write("                    <h1><p>ARE YOU READY TO DRINK?</p></h1>\r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("                <div id=\"description1\" class=\"w_ body\">\r\n");
      out.write("                    <h3><p>당신은 <span style=\"background-color:black\">&nbsp;WINEFINE </span> 을 즐길 준비가 되었습니까?</p></h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div id=\"description2\" class=\"w_ body text\">\r\n");
      out.write("                    <p>해당 사이트는 만 19세 이상 성인만 입장 가능합니다.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!--<form action=\"/winefine/entrance\" method=\"post\">-->\r\n");
      out.write("                    <div class=\"w_ body text\">\r\n");
      out.write("                        <input type=\"text\" id=\"birthYear\" placeholder=\"생년\" minlength=\"4\" maxlength=\"4\" required>\r\n");
      out.write("                        <input type=\"text\" id=\"birthMonth\" placeholder=\"월\" minlength=\"2\" maxlength=\"2\">\r\n");
      out.write("                        <input type=\"text\" id=\"birthDate\" placeholder=\"일\" minlength=\"2\" maxlength=\"2\">\r\n");
      out.write("                    </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("                    <div id=\"description3\" class=\"w_ body text\">\r\n");
      out.write("                        <p>\r\n");
      out.write("                            온라인 와인 판매사이트인 저희 WINEFINE은 올바른 음주 문화를 선도하기 위하여 노력하고 있으며,<br>\r\n");
      out.write("                            19세 미만 청소년에게 절대로 주류 판매를 하지 않습니다.\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("        \r\n");
      out.write("                    <div class=\"w_ bottom\">\r\n");
      out.write("                        <button class=\"btn\" type=\"button\" onclick=\"return enter();\">입 장 하 기</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                <!--</form>-->\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            function enter(){\r\n");
      out.write("                var birthYear = document.getElementById(\"birthYear\").value;\r\n");
      out.write("                var birthMonth = document.getElementById(\"birthMonth\").value;\r\n");
      out.write("                var birthDate = document.getElementById(\"birthDate\").value;\r\n");
      out.write("\r\n");
      out.write("                var sysYear = new Date();\r\n");
      out.write("                sysYear = sysYear.getFullYear();\r\n");
      out.write("\r\n");
      out.write("                var area = document.getElementById(\"description2\");\r\n");
      out.write("                \r\n");
      out.write("                var age = sysYear - birthYear;\r\n");
      out.write("                if( age > 0 && age >= 20 && age < 110 \r\n");
      out.write("                		&& birthMonth > 0 && birthMonth < 13 \r\n");
      out.write("                		&& birthDate > 0 && birthDate < 32){\r\n");
      out.write("                	location.href = \"/winefine/welcome\";\r\n");
      out.write("                }\r\n");
      out.write("                else if( age > 0 && age < 19 ){\r\n");
      out.write("                	area.style.color=\"yellow\";\r\n");
      out.write("                    area.innerHTML = \"죄송합니다. 와인파인은 19세 이상만 이용가능합니다.\"; \r\n");
      out.write("                    \r\n");
      out.write("                }\r\n");
      out.write("                else{\r\n");
      out.write("                	area.style.color=\"yellow\";\r\n");
      out.write("                    area.innerHTML = \"올바른 형식의 날짜가 아닙니다. 다시 확인해주세요.\";\r\n");
      out.write("                    \r\n");
      out.write("                    document.getElementById(\"birthYear\").select();\r\n");
      out.write("\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("             \r\n");
      out.write("    </body>\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
