/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-05-30 00:42:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.winefine.member.model.vo.Member;

public final class memberEnrollFirst_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/member/../common/header.jsp", Long.valueOf(1653820130454L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.winefine.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title> WINEFINE :D </title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("    div{\r\n");
      out.write("		box-sizing: border-box;\r\n");
      out.write("	}\r\n");
      out.write("	.wrap{\r\n");
      out.write("		width: 1200px;\r\n");
      out.write("		height: 1500px;\r\n");
      out.write("		margin: auto;\r\n");
      out.write("	}\r\n");
      out.write("	.w_{\r\n");
      out.write("		/* border: 1px solid red; */\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.top{\r\n");
      out.write("      	height: 10%;\r\n");
      out.write("    }\r\n");
      out.write("    .body{\r\n");
      out.write("        height: 70%;\r\n");
      out.write("    }\r\n");
      out.write("    .bottom{\r\n");
      out.write("        height: 20%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  .enroll-outer {\r\n");
      out.write("        width:1200px;\r\n");
      out.write("        height: 800px;\r\n");
      out.write("        margin:auto;\r\n");
      out.write("        /* margin-top: 50px; */\r\n");
      out.write("        box-sizing : border-box;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #enroll-info{\r\n");
      out.write("        width: 80%;\r\n");
      out.write("        height: 125px;\r\n");
      out.write("        background-color: rgb(248, 247, 248);\r\n");
      out.write("        text-align: left;\r\n");
      out.write("        border-radius:5px;\r\n");
      out.write("        font-size: larger;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .enroll-outer>div{\r\n");
      out.write("        height : 100%;\r\n");
      out.write("        float: left;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #enroll_1, #enroll_2{\r\n");
      out.write("        width:45%;\r\n");
      out.write("        height:100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #enroll_2>h1{\r\n");
      out.write("        color: rgb(119, 45, 96); \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("   #enroll_1 img{\r\n");
      out.write("        float: right;\r\n");
      out.write("        width:70%;\r\n");
      out.write("        height:480px;\r\n");
      out.write("        display:block;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("    #btn1{\r\n");
      out.write("        background-color: rgb(119, 45, 96);\r\n");
      out.write("        color: white;\r\n");
      out.write("        width:80%;\r\n");
      out.write("        height: 40px;\r\n");
      out.write("        border-radius:5px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        font-size:medium;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #btn1:hover{\r\n");
      out.write("        opacity : 0.7;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .enroll-area a{\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: gray;\r\n");
      out.write("        font-size: small;\r\n");
      out.write("        padding: 30px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"w_ top\" style=\"width: 1200px; margin:auto;\">\r\n");
      out.write("        <!-- 헤더 START-->\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
 
	// 로그인한 사용자 정보 뽑기
	Member loginUser = (Member)session.getAttribute("loginUser"); 
	// 서블릿에서 보낸 메세지 뽑기
	String alertMsg = (String)session.getAttribute("alertMsg");
	// 메인 화면으로 이동하는 경로 뽑기
	String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title> WINEFINE :D </title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- * 부트스트랩 영역 --------------------------------------------------------------------------->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write(" <!-- menubar영역은 모든 페이지마다 넣어주기로 했으니 얘한테 한번 넣어두면 include 되는 모든페이지에서 쓸 수 있겠쥬 ! ☆  -->\r\n");
      out.write("\r\n");
      out.write("<!-- swiper.js -->\r\n");
      out.write("<link\r\n");
      out.write("  rel=\"stylesheet\"  \r\n");
      out.write("  href=\"https://unpkg.com/swiper@8/swiper-bundle.min.css\"\r\n");
      out.write("/>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://unpkg.com/swiper@8/swiper-bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("    .topWrap {\r\n");
      out.write("        padding : 22px 0 21px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .logo {\r\n");
      out.write("        width: 400px;\r\n");
      out.write("        float: left;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .logo>a {\r\n");
      out.write("        margin-left: 30px; /* 로고의 왼쪽 여백 설정 */\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .top_right_menu { float: right;}\r\n");
      out.write("\r\n");
      out.write("    .top_right_menu .top_menu{\r\n");
      out.write("        list-style-type: none;\r\n");
      out.write("        float: left;\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("        padding-right: 15px;\r\n");
      out.write("        padding-left: 15px;\r\n");
      out.write("    }\r\n");
      out.write("    #top_service>a { margin-right: 30px;} /* 우측 상단 아이콘의 오른쪽 여백 설정 */\r\n");
      out.write("\r\n");
      out.write("    .menu {\r\n");
      out.write("        display: table-cell;\r\n");
      out.write("        height: 30px;\r\n");
      out.write("        width: 200px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: black;\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        display: block; \r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        line-height: 30px; /* 장평조절: 위~ 아래에서 가운데 조정 */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu a:hover {\r\n");
      out.write("        color:#6B325B;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu:after {\r\n");
      out.write("            display:block;\r\n");
      out.write("            content: '';\r\n");
      out.write("            border-bottom: solid 4px #6B325B;  \r\n");
      out.write("            transform: scaleX(0);  \r\n");
      out.write("            transition: transform 250ms ease-in-out;\r\n");
      out.write("            padding: 0px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu:hover:after { transform: scaleX(0.6); }\r\n");
      out.write("\r\n");
      out.write("    #top_mypage {\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #top_mypage button {\r\n");
      out.write("        padding-right: 17px;\r\n");
      out.write("        background: url(\"/winefine/resources/images/pc_gray_arrow.png\") no-repeat 100% 50%;\r\n");
      out.write("        border: 0;\r\n");
      out.write("        outline: none;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .mp_layer {\r\n");
      out.write("        display: none;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 150%;\r\n");
      out.write("        transform: translateX(-25%);\r\n");
      out.write("        border: 1px solid #ddd;\r\n");
      out.write("        z-index: 200;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .noLogin {\r\n");
      out.write("        width: 80px;\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        padding: 10px 8px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    li .mp_layer .noLogin a:first-child {\r\n");
      out.write("        margin-bottom: 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .noLogin a{\r\n");
      out.write("        display: block;\r\n");
      out.write("        font-size: 12px;\r\n");
      out.write("        color: #555;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 로그인후 */\r\n");
      out.write("    li .mp_layer {\r\n");
      out.write("        display: none;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 150%;\r\n");
      out.write("        transform: translateX(-25%);\r\n");
      out.write("        border: 1px solid #ddd;\r\n");
      out.write("        z-index: 200;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    li .mp_layer .onLogin {\r\n");
      out.write("        width: 180px;\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        padding: 10px 0 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .mp_layer .onLogin ul {\r\n");
      out.write("        padding-left: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .mp_layer .onLogin ul li {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding-top: 10px;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .mp_layer .onLogin ul li .top_line {\r\n");
      out.write("        border-top: 1px solid black;\r\n");
      out.write("        padding-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .mp_layer .onLogin .btn_txt {\r\n");
      out.write("        margin: 5px 10px 0 !important;\r\n");
      out.write("        padding-right: 0 !important;\r\n");
      out.write("        width: calc( 100% - 20px) !important;\r\n");
      out.write("        height: 30px !important;\r\n");
      out.write("        font-size: 13px !important;\r\n");
      out.write("        line-height: 30px !important;\r\n");
      out.write("        font-weight: 700 !important;\r\n");
      out.write("        background:#6B325B !important;\r\n");
      out.write("        display: inline-block !important;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"top\" >\r\n");
      out.write("        <div class=\"topWrap\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/main.do\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/winefine_logo.png\" width=\"250px\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul class=\"top_right_menu\">\r\n");
      out.write("                <li class=\"top_menu\" id=\"top_search\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/icon_search.png\" class=\"btn\" data-toggle=\"modal\" data-target=\"#searchModal\"\r\n");
      out.write("                    style=\"padding:0px\"></li>\r\n");
      out.write("                ");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("                    <li class=\"top_menu\" id=\"top_cart\"><a href=\"");
      out.print( contextPath );
      out.write("/loginForm.me\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/icon_cart.png\"></a></li>\r\n");
      out.write("                ");
 }
                   else { 
      out.write("\r\n");
      out.write("                    <li class=\"top_menu\" id=\"top_cart\"><a href=\"");
      out.print( contextPath );
      out.write("/list.ca\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/icon_cart.png\"></a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <!-- 로그인 된 상태가 아니라면 보일것-->\r\n");
      out.write("                ");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("                    <li class=\"top_menu\" id=\"top_mypage\">\r\n");
      out.write("                        <button type=\"button\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/icon_mypage.png\"></button>\r\n");
      out.write("                        <div class=\"mp_layer\">\r\n");
      out.write("                            <div class=\"noLogin\">\r\n");
      out.write("                                <a href=\"");
      out.print( contextPath );
      out.write("/loginForm.me\">로그인</a>\r\n");
      out.write("                                <a href=\"");
      out.print( contextPath );
      out.write("/enrollInfo.me\">회원가입</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                ");
 }
                   else if(!loginUser.getUserId().equals("admin")) { 
      out.write("\r\n");
      out.write("                    <!-- 로그인한 사람이 admin이 아니라면 보일것-->\r\n");
      out.write("                    <li class=\"top_menu\" id=\"top_mypage\">\r\n");
      out.write("                        <button type=\"button\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/icon_mypage.png\"></button>\r\n");
      out.write("                        <div class=\"mp_layer\">\r\n");
      out.write("                            <div class=\"onLogin\">\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><b>");
      out.print( loginUser.getUserName() );
      out.write("님</b></li>\r\n");
      out.write("                                    <li><b>WineFine입니다.</b></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                                <button class=\"btn_txt\" onclick=\"location.href='");
      out.print( contextPath );
      out.write("/myPage.me'\">마이페이지</button>\r\n");
      out.write("                                <br>\r\n");
      out.write("                                <button class=\"btn_txt\" onclick=\"location.href='");
      out.print( contextPath );
      out.write("/logout.me'\">로그아웃</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                ");
 }
                   else { 
      out.write("\r\n");
      out.write("                    <!-- 만약 로그인한 사람이 admin이라면 보일것 -->\r\n");
      out.write("                    <li class=\"top_menu\" id=\"top_mypage\"><a href=\"");
      out.print( contextPath );
      out.write("/main.admin\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/icon_admin.png\"></a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                <li class=\"top_menu\" id=\"top_service\"><a href=\"");
      out.print( contextPath );
      out.write("/list.no\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/icon_center.png\"></a></li>\r\n");
      out.write("                <!-- <li><a href=\"");
      out.print( contextPath );
      out.write("/logout.me\">로그아웃</a></li> -->\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <br clear=\"both\">\r\n");
      out.write("    <hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("    <div class=\"nav-area\" align=\"center\">\r\n");
      out.write("        <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/store.th?currentPage=1\">와인스토어</a></div>\r\n");
      out.write("        <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/views/board/soulWine.jsp\">소울와인찾기</a></div>\r\n");
      out.write("        <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.th?boardType=wine\">게시판</a></div>\r\n");
      out.write("        <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.no\">고객센터</a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("<br>\r\n");
      out.write("    \r\n");
      out.write("    <!-- The Modal -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"searchModal\" style=\"background-color: white; \">\r\n");
      out.write("        <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("        <div class=\"modal-content\" style=\"border-color: white;\">\r\n");
      out.write("        \r\n");
      out.write("            <!-- Modal Header -->\r\n");
      out.write("            <div class=\"modal-header\" style=\"border-color: white;\">\r\n");
      out.write("            <h4 class=\"modal-title\"></h4>\r\n");
      out.write("            <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Modal body -->\r\n");
      out.write("            <form action=\"");
      out.print( contextPath );
      out.write("/search.pr\" method=\"get\">\r\n");
      out.write("                <div class=\"modal-body\" style=\"width:1200px; height: 400px; border-color: white;\">\r\n");
      out.write("                    <b style=\"font-size: 100px;\">search</b><br>\r\n");
      out.write("                    <input type=\"text\" name=\"searchWord\" placeholder=\"원하시는 검색어를 입력하세요.\"\r\n");
      out.write("                        style=\"font-size: 50px; color:grey; width: 1000px; height: 100px; border: white;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Modal footer -->\r\n");
      out.write("                <div class=\"modal-footer\" style=\"border-color: white;\">\r\n");
      out.write("                        <input type=\"submit\" class=\"btn btn-secondary\" value=\"검색하기\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    	\r\n");
      out.write("        var message = \"");
      out.print( alertMsg );
      out.write("\";\r\n");
      out.write("        \r\n");
      out.write("        if(message != \"null\") { //로그인 정보가 넘어온 경우\r\n");
      out.write("            \r\n");
      out.write("            alert(message);\r\n");
      out.write("        \r\n");
      out.write("            ");
 session.removeAttribute("alertMsg"); 
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $(function () {\r\n");
      out.write("            $(\"#top_mypage button\").click(function () {\r\n");
      out.write("                if( $(\".mp_layer\").css(\"display\") == \"none\") {\r\n");
      out.write("\r\n");
      out.write("                    $(\".mp_layer\").css(\"display\", \"block\");\r\n");
      out.write("                }\r\n");
      out.write("                else {\r\n");
      out.write("                    $(\".mp_layer\").css(\"display\", \"none\");\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            $(\".btn_txt\").css(\"background-image\", \"url('')\");\r\n");
      out.write("            $(\".btn_txt\").css(\"padding-right\", 0);\r\n");
      out.write("            $(\".btn_txt\").css(\"padding-left\", 0);\r\n");
      out.write("            $(\".btn_txt\").css(\"outline\", \"auto\");\r\n");
      out.write("            $(\".btn_txt\").css(\"outline\", \"auto\");\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("        <!-- 헤더 END-->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ../ : 현재 폴더로부터 한번 빠져나감(즉, 현재 폴더로부터 한단계 상위 폴더로 이동) -->\r\n");
      out.write("    <div class=\"enroll-outer\">\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    <br><br>\r\n");
      out.write("        <div id=\"enroll_1\"><img src=\"/winefine/resources/images/wineEnroll.jpg\"></div>\r\n");
      out.write("        <div id=\"enroll_2\">\r\n");
      out.write("            <h1 align=\"center\">회원가입</h1>\r\n");
      out.write("            <hr><br><br>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"enroll-area\" align=\"center\">\r\n");
      out.write("               \r\n");
      out.write("                    <table>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <textarea rows=\"20\" style=\"resize:none;\" id=\"enroll-info\"> WINE-FINE은 19세 이상만 회원 가입 가능합니다. 가입을 원하시면 아래 [WINE-FINE 가입하기] 버튼을 눌러주세요.\r\n");
      out.write("                          </textarea>\r\n");
      out.write("                          <br><br><br>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        \r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <br>\r\n");
      out.write("                                <button type=\"button\" class=\"btn\" id=\"btn1\" onclick=\"enrollPage();\">WINE FINE 가입하기</button>\r\n");
      out.write("                                <br><br><br><br><hr>\r\n");
      out.write("                                <span>이미 회원이신가요?</span><a href=\"/winefine/loginForm.me\">로그인 하기</a></span>\r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        \r\n");
      out.write("                    </table>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("    <script>\r\n");
      out.write("        function enrollPage(){\r\n");
      out.write("\r\n");
      out.write("            location.href=\"/winefine/enrollForm.me\";\r\n");
      out.write("\r\n");
      out.write("        };\r\n");
      out.write("        \r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
