/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-05-30 01:04:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.winefine.oneqna.model.vo.Oneqna;
import com.winefine.member.model.vo.Member;

public final class myPage_005fview1on1Qna_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/member/../common/header.jsp", Long.valueOf(1653820130454L));
    _jspx_dependants.put("/views/member/../common/category-myPage.jsp", Long.valueOf(1653459668283L));
    _jspx_dependants.put("/views/member/../common/footer.jsp", Long.valueOf(1653850716226L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.winefine.oneqna.model.vo.Oneqna");
    _jspx_imports_classes.add("com.winefine.member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	ArrayList<Oneqna> list = (ArrayList<Oneqna>)request.getAttribute("list");


      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title> WINEFINE :D </title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("	div{\r\n");
      out.write("		box-sizing: border-box;\r\n");
      out.write("	}\r\n");
      out.write("	.wrap{\r\n");
      out.write("		width: 1200px;\r\n");
      out.write("		height: 1500px;\r\n");
      out.write("		margin: auto;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.w_{\r\n");
      out.write("		/* border: 1px solid red; */\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.top{\r\n");
      out.write("      	height: 10%;\r\n");
      out.write("    }\r\n");
      out.write("    .body{\r\n");
      out.write("        height: 70%;\r\n");
      out.write("    }\r\n");
      out.write("    .bottom{\r\n");
      out.write("        height: 20%;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /* - 구조 : body 영역_ 좌측 & 우측 분할 */\r\n");
      out.write("    .myPage-body{\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 97%;\r\n");
      out.write("    }\r\n");
      out.write("    .myPage-body td.body_l{\r\n");
      out.write("        width: 20%;\r\n");
      out.write("        vertical-align: top;\r\n");
      out.write("    }\r\n");
      out.write("    .myPage-body td.body_r{\r\n");
      out.write("        width: 80%;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /* 상세 항목 */\r\n");
      out.write("\r\n");
      out.write("    .delete{\r\n");
      out.write("        padding-left: 5%;\r\n");
      out.write("        width: 90%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    table img {\r\n");
      out.write("        width: 100px;\r\n");
      out.write("        height: 100px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("	#oneQ thead th{\r\n");
      out.write("		border-bottom: 1px solid black;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#oneQ tbody tr:hover {\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("		color: rgb(119, 45, 96);            \r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	button {\r\n");
      out.write("		background-color: rgb(119, 45, 96); ;\r\n");
      out.write("		color: white;\r\n");
      out.write("		border: none;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	button:hover {\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#oneQ td {\r\n");
      out.write("		padding: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("		<!-- top : hearder 삽입 영역 ------------------------------->\r\n");
      out.write("		<div class=\"w_ top\">\r\n");
      out.write("			<!-- 헤더 START-->\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("\r\n");
 
	// 로그인한 사용자 정보 뽑기
	Member loginUser = (Member)session.getAttribute("loginUser"); 
	// 서블릿에서 보낸 메세지 뽑기
	String alertMsg = (String)session.getAttribute("alertMsg");
	// 메인 화면으로 이동하는 경로 뽑기
	String contextPath = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title> WINEFINE :D </title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- * 부트스트랩 영역 --------------------------------------------------------------------------->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write(" <!-- menubar영역은 모든 페이지마다 넣어주기로 했으니 얘한테 한번 넣어두면 include 되는 모든페이지에서 쓸 수 있겠쥬 ! ☆  -->\r\n");
      out.write("\r\n");
      out.write("<!-- swiper.js -->\r\n");
      out.write("<link\r\n");
      out.write("  rel=\"stylesheet\"  \r\n");
      out.write("  href=\"https://unpkg.com/swiper@8/swiper-bundle.min.css\"\r\n");
      out.write("/>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://unpkg.com/swiper@8/swiper-bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("    .topWrap {\r\n");
      out.write("        padding : 22px 0 21px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .logo {\r\n");
      out.write("        width: 400px;\r\n");
      out.write("        float: left;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .logo>a {\r\n");
      out.write("        margin-left: 30px; /* 로고의 왼쪽 여백 설정 */\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .top_right_menu { float: right;}\r\n");
      out.write("\r\n");
      out.write("    .top_right_menu .top_menu{\r\n");
      out.write("        list-style-type: none;\r\n");
      out.write("        float: left;\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("        padding-right: 15px;\r\n");
      out.write("        padding-left: 15px;\r\n");
      out.write("    }\r\n");
      out.write("    #top_service>a { margin-right: 30px;} /* 우측 상단 아이콘의 오른쪽 여백 설정 */\r\n");
      out.write("\r\n");
      out.write("    .menu {\r\n");
      out.write("        display: table-cell;\r\n");
      out.write("        height: 30px;\r\n");
      out.write("        width: 200px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: black;\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        display: block; \r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        line-height: 30px; /* 장평조절: 위~ 아래에서 가운데 조정 */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu a:hover {\r\n");
      out.write("        color:#6B325B;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu:after {\r\n");
      out.write("            display:block;\r\n");
      out.write("            content: '';\r\n");
      out.write("            border-bottom: solid 4px #6B325B;  \r\n");
      out.write("            transform: scaleX(0);  \r\n");
      out.write("            transition: transform 250ms ease-in-out;\r\n");
      out.write("            padding: 0px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu:hover:after { transform: scaleX(0.6); }\r\n");
      out.write("\r\n");
      out.write("    #top_mypage {\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #top_mypage button {\r\n");
      out.write("        padding-right: 17px;\r\n");
      out.write("        background: url(\"/winefine/resources/images/pc_gray_arrow.png\") no-repeat 100% 50%;\r\n");
      out.write("        border: 0;\r\n");
      out.write("        outline: none;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .mp_layer {\r\n");
      out.write("        display: none;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 150%;\r\n");
      out.write("        transform: translateX(-25%);\r\n");
      out.write("        border: 1px solid #ddd;\r\n");
      out.write("        z-index: 200;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .noLogin {\r\n");
      out.write("        width: 80px;\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        padding: 10px 8px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    li .mp_layer .noLogin a:first-child {\r\n");
      out.write("        margin-bottom: 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .noLogin a{\r\n");
      out.write("        display: block;\r\n");
      out.write("        font-size: 12px;\r\n");
      out.write("        color: #555;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 로그인후 */\r\n");
      out.write("    li .mp_layer {\r\n");
      out.write("        display: none;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 150%;\r\n");
      out.write("        transform: translateX(-25%);\r\n");
      out.write("        border: 1px solid #ddd;\r\n");
      out.write("        z-index: 200;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    li .mp_layer .onLogin {\r\n");
      out.write("        width: 180px;\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        padding: 10px 0 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .mp_layer .onLogin ul {\r\n");
      out.write("        padding-left: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .mp_layer .onLogin ul li {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding-top: 10px;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .mp_layer .onLogin ul li .top_line {\r\n");
      out.write("        border-top: 1px solid black;\r\n");
      out.write("        padding-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .mp_layer .onLogin .btn_txt {\r\n");
      out.write("        margin: 5px 10px 0 !important;\r\n");
      out.write("        padding-right: 0 !important;\r\n");
      out.write("        width: calc( 100% - 20px) !important;\r\n");
      out.write("        height: 30px !important;\r\n");
      out.write("        font-size: 13px !important;\r\n");
      out.write("        line-height: 30px !important;\r\n");
      out.write("        font-weight: 700 !important;\r\n");
      out.write("        background:#6B325B !important;\r\n");
      out.write("        display: inline-block !important;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"top\" >\r\n");
      out.write("        <div class=\"topWrap\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/main.do\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/winefine_logo.png\" width=\"250px\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul class=\"top_right_menu\">\r\n");
      out.write("                <li class=\"top_menu\" id=\"top_search\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/icon_search.png\" class=\"btn\" data-toggle=\"modal\" data-target=\"#searchModal\"\r\n");
      out.write("                    style=\"padding:0px\"></li>\r\n");
      out.write("                ");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("                    <li class=\"top_menu\" id=\"top_cart\"><a href=\"");
      out.print( contextPath );
      out.write("/loginForm.me\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/icon_cart.png\"></a></li>\r\n");
      out.write("                ");
 }
                   else { 
      out.write("\r\n");
      out.write("                    <li class=\"top_menu\" id=\"top_cart\"><a href=\"");
      out.print( contextPath );
      out.write("/list.ca\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/icon_cart.png\"></a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <!-- 로그인 된 상태가 아니라면 보일것-->\r\n");
      out.write("                ");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("                    <li class=\"top_menu\" id=\"top_mypage\">\r\n");
      out.write("                        <button type=\"button\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/icon_mypage.png\"></button>\r\n");
      out.write("                        <div class=\"mp_layer\">\r\n");
      out.write("                            <div class=\"noLogin\">\r\n");
      out.write("                                <a href=\"");
      out.print( contextPath );
      out.write("/loginForm.me\">로그인</a>\r\n");
      out.write("                                <a href=\"");
      out.print( contextPath );
      out.write("/enrollInfo.me\">회원가입</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                ");
 }
                   else if(!loginUser.getUserId().equals("admin")) { 
      out.write("\r\n");
      out.write("                    <!-- 로그인한 사람이 admin이 아니라면 보일것-->\r\n");
      out.write("                    <li class=\"top_menu\" id=\"top_mypage\">\r\n");
      out.write("                        <button type=\"button\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/icon_mypage.png\"></button>\r\n");
      out.write("                        <div class=\"mp_layer\">\r\n");
      out.write("                            <div class=\"onLogin\">\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><b>");
      out.print( loginUser.getUserName() );
      out.write("님</b></li>\r\n");
      out.write("                                    <li><b>WineFine입니다.</b></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                                <button class=\"btn_txt\" onclick=\"location.href='");
      out.print( contextPath );
      out.write("/myPage.me'\">마이페이지</button>\r\n");
      out.write("                                <br>\r\n");
      out.write("                                <button class=\"btn_txt\" onclick=\"location.href='");
      out.print( contextPath );
      out.write("/logout.me'\">로그아웃</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                ");
 }
                   else { 
      out.write("\r\n");
      out.write("                    <!-- 만약 로그인한 사람이 admin이라면 보일것 -->\r\n");
      out.write("                    <li class=\"top_menu\" id=\"top_mypage\"><a href=\"");
      out.print( contextPath );
      out.write("/main.admin\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/icon_admin.png\"></a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                <li class=\"top_menu\" id=\"top_service\"><a href=\"");
      out.print( contextPath );
      out.write("/list.no\"><img src=\"");
      out.print( contextPath );
      out.write("/resources/images/icon_center.png\"></a></li>\r\n");
      out.write("                <!-- <li><a href=\"");
      out.print( contextPath );
      out.write("/logout.me\">로그아웃</a></li> -->\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <br clear=\"both\">\r\n");
      out.write("    <hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("    <div class=\"nav-area\" align=\"center\">\r\n");
      out.write("        <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/store.th?currentPage=1\">와인스토어</a></div>\r\n");
      out.write("        <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/views/board/soulWine.jsp\">소울와인찾기</a></div>\r\n");
      out.write("        <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.th?boardType=wine\">게시판</a></div>\r\n");
      out.write("        <div class=\"menu\"><a href=\"");
      out.print( contextPath );
      out.write("/list.no\">고객센터</a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("<br>\r\n");
      out.write("    \r\n");
      out.write("    <!-- The Modal -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"searchModal\" style=\"background-color: white; \">\r\n");
      out.write("        <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("        <div class=\"modal-content\" style=\"border-color: white;\">\r\n");
      out.write("        \r\n");
      out.write("            <!-- Modal Header -->\r\n");
      out.write("            <div class=\"modal-header\" style=\"border-color: white;\">\r\n");
      out.write("            <h4 class=\"modal-title\"></h4>\r\n");
      out.write("            <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Modal body -->\r\n");
      out.write("            <form action=\"");
      out.print( contextPath );
      out.write("/search.pr\" method=\"get\">\r\n");
      out.write("                <div class=\"modal-body\" style=\"width:1200px; height: 400px; border-color: white;\">\r\n");
      out.write("                    <b style=\"font-size: 100px;\">search</b><br>\r\n");
      out.write("                    <input type=\"text\" name=\"searchWord\" placeholder=\"원하시는 검색어를 입력하세요.\"\r\n");
      out.write("                        style=\"font-size: 50px; color:grey; width: 1000px; height: 100px; border: white;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Modal footer -->\r\n");
      out.write("                <div class=\"modal-footer\" style=\"border-color: white;\">\r\n");
      out.write("                        <input type=\"submit\" class=\"btn btn-secondary\" value=\"검색하기\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    	\r\n");
      out.write("        var message = \"");
      out.print( alertMsg );
      out.write("\";\r\n");
      out.write("        \r\n");
      out.write("        if(message != \"null\") { //로그인 정보가 넘어온 경우\r\n");
      out.write("            \r\n");
      out.write("            alert(message);\r\n");
      out.write("        \r\n");
      out.write("            ");
 session.removeAttribute("alertMsg"); 
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $(function () {\r\n");
      out.write("            $(\"#top_mypage button\").click(function () {\r\n");
      out.write("                if( $(\".mp_layer\").css(\"display\") == \"none\") {\r\n");
      out.write("\r\n");
      out.write("                    $(\".mp_layer\").css(\"display\", \"block\");\r\n");
      out.write("                }\r\n");
      out.write("                else {\r\n");
      out.write("                    $(\".mp_layer\").css(\"display\", \"none\");\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            $(\".btn_txt\").css(\"background-image\", \"url('')\");\r\n");
      out.write("            $(\".btn_txt\").css(\"padding-right\", 0);\r\n");
      out.write("            $(\".btn_txt\").css(\"padding-left\", 0);\r\n");
      out.write("            $(\".btn_txt\").css(\"outline\", \"auto\");\r\n");
      out.write("            $(\".btn_txt\").css(\"outline\", \"auto\");\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("			<!-- 헤더 END-->\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<!-- body : 카테고리 페이지 바디 영역 --------------------------------------------->\r\n");
      out.write("       <div class=\"w_ body\">\r\n");
      out.write("       \r\n");
      out.write("        <br>   \r\n");
      out.write("           <!-- body left(카테고리) & right(내용)-->\r\n");
      out.write("            <table class=\"myPage-body\">\r\n");
      out.write("                <td class=\"body_l\">\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("     #leftNavi {\r\n");
      out.write("            list-style-type : none;\r\n");
      out.write("            margin : 0px;\r\n");
      out.write("            padding : 0px;\r\n");
      out.write("            height : 100%;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    #leftNavi li {\r\n");
      out.write("        width : 100%;\r\n");
      out.write("        height : 11%;\r\n");
      out.write("        text-align : center;\r\n");
      out.write("    }\r\n");
      out.write("    .left_menu a {\r\n");
      out.write("        color: #000;\r\n");
      out.write("        text-decoration : none;\r\n");
      out.write("        margin:0;\r\n");
      out.write("        text-transform:uppercase; \r\n");
      out.write("        font-size : 20px;\r\n");
      out.write("        font-weight : bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .left_menu_ a {\r\n");
      out.write("        color: #000;\r\n");
      out.write("        text-decoration : none;\r\n");
      out.write("        margin:0;\r\n");
      out.write("        text-transform:uppercase; \r\n");
      out.write("        font-size : 20px;\r\n");
      out.write("        font-weight : bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .left_menu::after {\r\n");
      out.write("        display:block;\r\n");
      out.write("        content: '';\r\n");
      out.write("        border-bottom: solid 3px rgb(107, 50, 91);  \r\n");
      out.write("        transform: scaleX(0);  \r\n");
      out.write("        transition: transform 250ms ease-in-out;\r\n");
      out.write("    }\r\n");
      out.write("    .left_menu:hover::after { transform: scaleX(0.4); }\r\n");
      out.write("    #mp1:hover::after { transform: scaleX(0.5); }\r\n");
      out.write("    #mp2:hover::after { transform: scaleX(0.65); }\r\n");
      out.write("    #mp3:hover::after { transform: scaleX(0.65); }\r\n");
      out.write("    #mp4:hover::after { transform: scaleX(0.5); }\r\n");
      out.write("    \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"content\">\r\n");
      out.write("        <div id=\"content_1\" align=\"center\">\r\n");
      out.write("            <ul id=\"leftNavi\">\r\n");
      out.write("                <b style=\"font-size:24px;\">마이페이지</b>\r\n");
      out.write("                <hr  color=\"black\" style=\"border: 1px solid black\">\r\n");
      out.write("                <li class=\"left_menu_\"><a>나의쇼핑</a></li><hr color=\"gray\">\r\n");
      out.write("                <li class=\"left_menu\"><a href=\"/winefine/myPage.me\">주문내역</a></li><br>\r\n");
      out.write("                <li class=\"left_menu\"><a href=\"/winefine/list.ca\">장바구니</a></li><hr color=\"gray\">\r\n");
      out.write("                <li class=\"left_menu_\"><a>개인정보</a></li><hr color=\"gray\">\r\n");
      out.write("                <li class=\"left_menu\" id=\"mp1\"><a href=\"/winefine/checkForm.me\">회원정보수정</a></li><br>\r\n");
      out.write("                <li class=\"left_menu\" id=\"mp2\"><a href=\"/winefine/qna.me\">상품문의내역확인</a></li><br>\r\n");
      out.write("                <li class=\"left_menu\" id=\"mp3\"><a href=\"/winefine/1on1.me\">1대1문의내역확인</a></li><br>\r\n");
      out.write("                <li class=\"left_menu\" id=\"mp4\"><a href=\"/winefine/review.me\">리뷰내역확인</a></li><br>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div> \r\n");
      out.write("        <!-- <div id=\"content_2\"></div> -->\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("                </td>\r\n");
      out.write("                <td class=\"body_r\">\r\n");
      out.write("                    <div class=\"delete\">\r\n");
      out.write("                        <!-- <h2>상품 주문내역</h2> -->\r\n");
      out.write("						<b style=\"font-size:24px;\">1대1 문의 내역</b>\r\n");
      out.write("			    		<hr style=\"border: 1px solid black\">\r\n");
      out.write("			\r\n");
      out.write("					<table id=\"oneQ\" style=\"text-align: center\">\r\n");
      out.write("			            <thead>\r\n");
      out.write("			                <tr>\r\n");
      out.write("								<th width=\"100\">문의번호</th>\r\n");
      out.write("			                    <th width=\"600\">제목</th>\r\n");
      out.write("			                    <th width=\"100\">작성일</th>\r\n");
      out.write("			                    <th width=\"100\">답변상태</th>\r\n");
      out.write("			                </tr>\r\n");
      out.write("			            </thead>\r\n");
      out.write("			            <tbody>\r\n");
      out.write("							");
 if(list.isEmpty()) { 
      out.write("\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td height=\"300\" colspan=\"3\">1대1 문의내역이 없습니다.</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("							");
 } 
							   else { 
      out.write("\r\n");
      out.write("							   ");
 for(Oneqna one : list) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("				                <tr class=\"nn\">\r\n");
      out.write("									<td>");
      out.print( one.getOneqnaNo() );
      out.write("</td>\r\n");
      out.write("				                    <td>");
      out.print( one.getOneqnaTitle() );
      out.write("</td>\r\n");
      out.write("				                    <td>");
      out.print( one.getCreateDate() );
      out.write("</td>\r\n");
      out.write("				                    <td>");
 if(one.getAnswerYn().equals("Y")) { 
      out.write("\r\n");
      out.write("				                    		답변완료\r\n");
      out.write("				                    	");
 }
				                           else { 
      out.write("\r\n");
      out.write("				                               	답변중\r\n");
      out.write("				                        ");
 } 
      out.write("\r\n");
      out.write("				                   </td>\r\n");
      out.write("				                </tr>\r\n");
      out.write("				                ");
 } 
      out.write("\r\n");
      out.write("			                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("			            </tbody>\r\n");
      out.write("			        </table>\r\n");
      out.write("			\r\n");
      out.write("			        <!-- <table border=\"1\">\r\n");
      out.write("			            <thead>\r\n");
      out.write("			                <tr>\r\n");
      out.write("			                    <th width=\"600\">제목</th>\r\n");
      out.write("			                    <th width=\"150\">작성일</th>\r\n");
      out.write("			                    <th width=\"150\">답변상태</th>\r\n");
      out.write("			                </tr>\r\n");
      out.write("			            </thead>\r\n");
      out.write("			            <tbody>\r\n");
      out.write("			                <tr height=\"300\">\r\n");
      out.write("			                    <td colspan=\"3\" style=\"text-align: center; font-size: 18px;\">작성된 문의가 없습니다.</td>          \r\n");
      out.write("			                </tr>\r\n");
      out.write("			            </tbody>\r\n");
      out.write("			        </table> -->\r\n");
      out.write("			\r\n");
      out.write("						<br>\r\n");
      out.write("						<div align=\"center\">\r\n");
      out.write("							\r\n");
      out.write("							<a href=\"");
      out.print( contextPath );
      out.write("/list.on\" class=\"btn btn-secondary\" style=\"background-color: rgb(119, 45, 96); ;\r\n");
      out.write("								color: white; border: none;\">1대1문의</a>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("           </table>\r\n");
      out.write("       </div>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("       \r\n");
      out.write("        <!-- bottom : 푸터바 영역 ---------------------------------------------------->\r\n");
      out.write("        <div class=\"w_ bottom\">\r\n");
      out.write("            \r\n");
      out.write("            <!-- 푸터바 START-->\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title> WINEFINE :D </title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* 가이드라인*/\r\n");
      out.write("        div,table{\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        body, p{\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* 구조잡기*/\r\n");
      out.write("        .bottom{\r\n");
      out.write("            width: 1200px;\r\n");
      out.write("            /* 전체 height 1500px의 20%로 가정*/\r\n");
      out.write("            height: 300px;\r\n");
      out.write("            margin:auto;\r\n");
      out.write("            /* position: absolute; */\r\n");
      out.write("        }\r\n");
      out.write("        .footer1, .footer3{\r\n");
      out.write("            width: 1200px;\r\n");
      out.write("            height: 15%;\r\n");
      out.write("        }\r\n");
      out.write("        .footer2{\r\n");
      out.write("            width: 1200px;\r\n");
      out.write("            height: 70%;\r\n");
      out.write("        }\r\n");
      out.write("        .left, .right{\r\n");
      out.write("            width: 25%;\r\n");
      out.write("            vertical-align: middle;\r\n");
      out.write("        }\r\n");
      out.write("        .center{\r\n");
      out.write("            width:50%;\r\n");
      out.write("        }\r\n");
      out.write("        #table{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 세부 사항 */\r\n");
      out.write("        .footer{\r\n");
      out.write("            background-color: #333;\r\n");
      out.write("            border-bottom: 1px solid gray;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .table{\r\n");
      out.write("            color:grey;\r\n");
      out.write("        }\r\n");
      out.write("        .footer1{\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        .footer1, .footer3{\r\n");
      out.write("            line-height: 40px;\r\n");
      out.write("        }\r\n");
      out.write("        .text{\r\n");
      out.write("            color:white;\r\n");
      out.write("        }\r\n");
      out.write("        a{\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("        a:hover{\r\n");
      out.write("            color: gray;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("        #logo{\r\n");
      out.write("            color: #6B325B;\r\n");
      out.write("        }\r\n");
      out.write("        .center, #copyright{\r\n");
      out.write("            font-size: 80%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 잡기술 */\r\n");
      out.write("        .bottom .hidden_info {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bottom .hidden_info {\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bottom .hidden_info .hidden_info_close {\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            margin-left: -50px;\r\n");
      out.write("            border: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bottom .hidden_info .hidden_info_close {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            top: -30px;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            line-height: 30px;\r\n");
      out.write("            background: #333 url(\"/winefine/resources/images/btn_hidden_info_close.png\") no-repeat 50%;\r\n");
      out.write("            border-radius: 5px 5px 0 0;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            text-indent: -9999px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #copyright:hover {\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        } \r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- 모든페이지 > bottom 영역에 들어갈 푸터바         -->\r\n");
      out.write("    <!-- 참고) 푸터바 영역은 전체 height:1500px의 20% 할당-->\r\n");
      out.write("    <div class=\"bottom\">\r\n");
      out.write("        <br><br>\r\n");
      out.write("        <div class=\"hidden_info\">\r\n");
      out.write("            <button type=\"button\" class=\"hidden_info_close\" onclick=\"footClose();\"></button>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"footer footer1\">\r\n");
      out.write("                <span class=\"text\"><a href=\"/winefine/prepare.do\">브랜드소개</a> &nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp; </span>\r\n");
      out.write("                <span class=\"text\"><a href=\"/winefine/list.co\">오시는 길</a> &nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp; </span>  \r\n");
      out.write("                <span class=\"text\"><a href=\"/winefine/prepare.do\">이용약관</a> &nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp; </span> \r\n");
      out.write("                <span class=\"text\"><a href=\"/winefine/prepare.do\">개인정보취급방침</a> &nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp; </span> \r\n");
      out.write("                <span class=\"text\"><a href=\"/winefine/list.no\">고객센터</a> </span> \r\n");
      out.write("            </div>\r\n");
      out.write("    \r\n");
      out.write("            <div class=\"footer footer2\">\r\n");
      out.write("                <table id=\"table\">\r\n");
      out.write("                    <td class=\"left\">\r\n");
      out.write("                        <h1 id=\"logo\">WINEFINE</h1>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td class=\"table center\">\r\n");
      out.write("                        (주)와인파인 대표자: WINEFINE<br>\r\n");
      out.write("                        사업자등록번호: [KH-452-02-00843] 통신판매업자신고번호: 제2022-서울 영등포 - NO4호<br>\r\n");
      out.write("                        대표번호: KH-1640-5091 주소: 서울특별시 영등포구 선유동2로 57 이레빌딩 19F, 20F<br>\r\n");
      out.write("                        개인정보관리자: KH(khlove@iei.co.kr)<br>\r\n");
      out.write("                        대표메일 winefine@iei.co.kr 사이트명: 와인파인<br>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        Bank Accounts : KH은행 027-142321-01-004 주식회사 와인파인<br>\r\n");
      out.write("                        CS Center : 1661-5091 AM 10:00 ~ PM 6:00<br>\r\n");
      out.write("                        (점심시간 PM 1:00~ 2:00) ( WEEKEND/HOLIDAY OFF )<br>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td class=\"table right\">\r\n");
      out.write("                        <h5>고객센터 운영시간</h5>\r\n");
      out.write("                        평일 10:00 - 18:00<br>\r\n");
      out.write("                        점심시간 13:00 - 14:00<br>\r\n");
      out.write("                        주말 및 공휴일 휴무\r\n");
      out.write("                    </td>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("            \r\n");
      out.write("        <div class=\"footer footer3\" id=\"copy\" >\r\n");
      out.write("            <p id =\"copyright\" class=\"text\" onclick=\"footOpen();\">Copyright © 2022 WINEFINE Information All Right Reserved</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("\r\n");
      out.write("        function footClose() {\r\n");
      out.write("\r\n");
      out.write("            // $(\".hidden_info\").css(\"display\", \"none\");\r\n");
      out.write("            $(\".hidden_info\").css(\"visibility\", \"hidden\");\r\n");
      out.write("            // $(\".hidden_info\").hide();\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function footOpen() {\r\n");
      out.write("            // $(\".hidden_info\").css(\"display\", \"block\");\r\n");
      out.write("            $(\".hidden_info\").css(\"visibility\", \"visible\");\r\n");
      out.write("            // $(\".hidden_info\").show();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $(function() {\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("            <!-- 푸터바 END-->\r\n");
      out.write("         \r\n");
      out.write("        </div>\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	<script>\r\n");
      out.write("\r\n");
      out.write("		// function toOne() {\r\n");
      out.write("		// 	location.href=\"");
      out.print( contextPath );
      out.write("/list.on\";\r\n");
      out.write("		// } 버튼이 안먹음???\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		$(function () {\r\n");
      out.write("			$(\".nn\").click(function () {\r\n");
      out.write("				// console.log(\"클릭\")\r\n");
      out.write("				var ono = $(this).children().eq(0).text();\r\n");
      out.write("				console.log(ono);\r\n");
      out.write("\r\n");
      out.write("				location.href=\"");
      out.print( contextPath );
      out.write("/view1On1.me?ono=\" + ono;\r\n");
      out.write("				// 이동이 아니라 상세로 보게끔 모달창을 띄워야하나? ... 고민\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			//$(\"button[id=1on1]\").click(function () {\r\n");
      out.write("				//console.log(\"클릭됨\");\r\n");
      out.write("				//location.href=\"");
      out.print( contextPath );
      out.write("/list.on\";\r\n");
      out.write("				// 고객센터의 1대1 문의 화면으로 넘겨주기.\r\n");
      out.write("			//});\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
